### ISSUE TITLE
DroidSeries Import doesn't work

### ISSUE THREAD

**Issue by Shadouw** [ltguillaume/droidshows#1]
Hi, I'd like to move from DroidSeries to DroidShows V5.3. When I import the database file (as described in FAQ, Android 4.4.2 rooted) DroidShows imports it and says that  it successfully restored the backup. But there are no shows. When I then export, the exported file has same size as the imported file.

**Comment by ltguillaume** [comment]
Hi! Could you send me the database perhaps? I'll have a look at it right away :)
You can upload it here (for the next couple of days): [link removed]

**Comment by Shadouw** [comment]
I've uploaded it. Thank you very much.

**Comment by ltguillaume** [comment]
Cool. I've found the issue: DroidShows has been forked from a fork by https://github.com/McKael, who added the passiveStatus for shows (in DroidShows: enable/disable show). The field for this feature has not been added to your database yet. Fixing it now.

**Comment by ltguillaume** [comment]
Fixed and tested with your database. You can find the new release here: https://github.com/ltGuillaume/DroidShows/releases

**Comment by Shadouw** [comment]
Cool, I successfully tested the latest release, works now. Thank you very much.
