### ISSUE TITLE
Reverse sorting order from Seasons

### ISSUE THREAD

**Issue by cybalkan** [ltguillaume/droidshows#101]
Because your no options for season top and bottom row...

Please Add
Display the newest season first.

Thanks!

See photo:
![Untitled](https://user-images.githubusercontent.com/29343328/105490308-4029fd00-5cbd-11eb-8060-1566227d5bf1.png)

**Comment by ltguillaume** [comment]
DroidShows already scrolls automatically to the first season with unseen episodes (if that season isn't already shown on screen). I think that suffices.
