### ISSUE TITLE
Feature request: Option to disable IMDB rating 

### ISSUE THREAD

**Issue by ghost** [ltguillaume/droidshows#102]
Hi,
An IMDB rating is shown when looking at individual episodes. Would it be possible to add an option that disables this (if its not too much trouble)

Thanks

**Comment by ltguillaume** [comment]
Sorry, I won't be removing this. I think it would be too much of a hassle to create a whole configuration for something that can't _really_ be in the way to anyone.

I do appreciate you asking, and I also know that sometimes the IMDb score is 0 in the database of TVDB, but the score also serves as a button to open the IMDB episode page.
