### ISSUE TITLE
Broken IMDb Searches Due To the "&" Character... 

### ISSUE THREAD

**Issue by Ibuprophen** [ltGuillaume/DroidShows#109]
Hello Again My Friend @ltGuillaume! 

I'm not sure if you're aware of this and I'll just provide an example that (I hope) will explain what I'm referring to. 

Within the App, If I first go to the TV show "Law & Order" and then "Season 8" and then "Episode 22" that's titled "Damaged". 

When I select the IMDb link, it will then go to the following link... 

https://m.imdb.com/find?q=Law%20&%20Order%20Damaged

... that's not providing very good search results because of the ampersand (aka "&"). 

With that stated... 

Is there a way that IMDb searches that has the "&" character be changed to the word "and". 

For example... 

If I take the IMDb search link (above) and add the word "and" as follows... 

https://m.imdb.com/find?q=Law%20and%20Order%20Damaged

... you will then see that the first choice of the search results is exactly the correct/specific episode being searched for. 

So ultimately, if the searches for something that has/needs the ampersand character "&" could really be helpful if those specific IMDb search links would help out tremendously if the app would replace it with the word "and" because those search links remove the "&" character that kinda breaks the search links with bad search results. 

I really tried my best to explain this (in a couple of ways) the best way I could via text. 

Please let me know if you require any further information and such... 👍 

~Ibuprophen

**Comment by ltguillaume** [comment]
Could you try this build (for all external sources, not just IMDB, and for IMDB from both Episode and Show Details if search is used)?
[DroidShows_7.11.4_AmpersandFix.zip](https://github.com/ltGuillaume/DroidShows/files/8402793/DroidShows_7.11.4_AmpersandFix.zip)

**Comment by Ibuprophen** [comment]
Unfortunately... It provided the same type of Results @ltGuillaume as before because the search is now for "Law amp Order Damaged" as reflected by the following link from the App. 

https://m.imdb.com/find?q=Law%20&amp&%20Order%20Damaged

So you can try/test this out, the examples I had previously & currently provided, was for "Season 8 Episode 22" of the original "Law & Order" Television Series. 

Thank you very much for your time and support! :-)) 


~Ibuprophen

**Comment by ltguillaume** [comment]
[DroidShows_7.11.4a_AmpersandFix.zip](https://github.com/ltGuillaume/DroidShows/files/8402882/DroidShows_7.11.4a_AmpersandFix.zip)

Please try again 🙈

**Comment by Ibuprophen** [comment]
EUREKA! 

The search link reflects the results for "Law & Order Damaged" that fixes the minor issue. 

Thank you SO much for your time, patience and support for this great app My Friend! 🥇 

I'll keep you informed of anything I run into down the road. Perfect! 👍 

I'll close this issue as being resolved. 


~Ibuprophen

**Comment by ltguillaume** [comment]
Great! Thanks for reporting 🙂
