### ISSUE TITLE
Inside a show, focus next not viewed season/episode

### ISSUE THREAD

**Issue by ghost** [ltguillaume/droidshows#11]
Hi!

This is a feature request. I think this could make more comfortable to use the app, since in shows with a lot of seasons or episodes per season, you always have to scroll to your next season/episode.

I don't know of this is possible.

Thank you for your work!

**Comment by ltguillaume** [comment]
I'll have a look asap, thanks!

**Comment by ltguillaume** [comment]
@helfio Check it out.
[DroidShows_6.6.zip](https://github.com/ltGuillaume/DroidShows/files/113527/DroidShows_6.6.zip)

**Comment by ghost** [comment]
This is great!! Thank you very much :)
