### ISSUE TITLE
Image not downloading for a specific show

### ISSUE THREAD

**Issue by p3titbo3uf** [ltGuillaume/DroidShows#111]
Thank you for the great work !

I've encountered an strange issue : when a specific show is added to my regular DroidShows list, the little poster on the left is not downloading, as you can see on the following image (the name of the show is « Chair tendre », but I guess you would have find out that).
![signal-2023-04-11-161723_002](https://user-images.githubusercontent.com/105296220/231192245-12af84b5-63a9-4935-b328-68b100621260.png)

At first I thought, as it was a French show, the poster wasn't set on the tvdb page of the show explaining this behavior. But this is not the case because the poster is properly set, as you can see [here](https://thetvdb.com/series/chair-tendre).

Is there something I'm doing wrong ? Has someone already witnessed this issue ?

**Comment by ltguillaume** [comment]
Thx for reporting! I'll have a look later today.

Strange premise of that show, though: why would anyone have only one year to figure out who they are? I must be missing some context about why the timing of such surgery is important maybe?

**Comment by ltguillaume** [comment]
Strange stuff! The API does not pass on a URL for the poster:
```
<?xml version="1.0" encoding="UTF-8"?>
<Data><Series><id>418015</id><Actors>|Angèle Metzger|Saül Benchetrit|Daphné Bürki|Grégoire Colin|Paola Locatelli|Marin Judas|Léna Garrel|Régis Marvin Merveille N&#39;Kissi Moggzi|Andréa Furet|Najim Zeghoudi|Lysandre Nury|Océan|</Actors><Airs_DayOfWeek></Airs_DayOfWeek><Airs_Time>12:00 AM</Airs_Time><ContentRating></ContentRating><FirstAired>2022-09-23</FirstAired><Genre>|Comedy|Drama|</Genre><IMDB_ID>tt1892968</IMDB_ID><Language>en</Language><Network>Slash</Network><NetworkID>1246</NetworkID><Overview>Sasha is the new high school girl, she leaves no one indifferent. Sasha was born intersex. Until last summer, she was a boy. She has one year to find out who she is and to decide if she will have surgery at the end of the year.</Overview><Rating>0</Rating><RatingCount>0</RatingCount><Runtime>26</Runtime><SeriesID></SeriesID><SeriesName>Chair tendre</SeriesName><Status>Continuing</Status><added>2022-03-20 01:05:04</added><addedBy></addedBy><banner>v4/series/418015/banners/635756fb70c1d.jpg</banner><fanart>v4/series/418015/backgrounds/623ee6ddd5bba.jpg</fanart><lastupdated>1674648950</lastupdated><poster></poster><zap2it_id></zap2it_id></Series></Data>
```
See? `<poster></poster>`

I've added a new poster, that's actually following the guidelines, so perhaps this one will eventually be picked up by the API.

**Comment by ltguillaume** [comment]
So I've added the poster while specifying the language of the text on the poster (French), and I see the poster if you choose French for synopsis language in DroidShows. Is this okay for you?

**Comment by p3titbo3uf** [comment]
It works ! Thanks a lot :)

**Comment by p3titbo3uf** [comment]
> Thx for reporting! I'll have a look later today.
> 
> Strange premise of that show, though: why would anyone have only one year to figure out who they are? I must be missing some context about why the timing of such surgery is important maybe?

It is the first time I'm reading that : I don't find the abstract very relevant... The show is about trans-identity and the questions one can have along that path. I think it is very well realised, I recommand it ;)

**Comment by ltguillaume** [comment]
> It works ! Thanks a lot :)

Great! 😃

> > Thx for reporting! I'll have a look later today.
> > Strange premise of that show, though: why would anyone have only one year to figure out who they are? I must be missing some context about why the timing of such surgery is important maybe?
> 
> It is the first time I'm reading that : I don't find the abstract very relevant... The show is about trans-identity and the questions one can have along that path. I think it is very well realised, I recommand it ;)

Yeah, I reckon it's just the way it was phrased and the lack of context in the synopsis I read that made it look like the show's completely hinged upon a very constructed ultimatum. I may have a look at it later, thx!

Closing!
