### ISSUE TITLE
Not compatible with Android 14?

### ISSUE THREAD

**Issue by casperklein** [ltGuillaume/DroidShows#114]
I updated my phone to Android 14 some time ago. Recently I noticed, that I am using not the latest version of droidshows, but an older one (`7.11.3`)  you provided [here](https://github.com/ltguillaume/droidshows/issues/38#issuecomment-1013804095). When I try to install `7.11.4`, I get an error, that my device is not compatible with the app.

With the exception of https://github.com/ltguillaume/droidshows/issues/107 (no big issue for me), the app works perfectly for me. So I think it's just some meta data somewhere that the app is only compatible with Android <=13, which prevents updates/installation.

**Comment by ltguillaume** [comment]
Funny, had the same thing yesterday 😛

This is a release with some fixes that I never committed to Codeberg/GitHub, larger cover sizes and a simple fix to allow installation on Android 14.

[DroidShows_7.11.7_BiggerCovers270px+(canMark)NextEpisodeFixSDK23.zip](https://github.com/ltguillaume/droidshows/files/14376782/DroidShows_7.11.7_BiggerCovers270px%2B.canMark.NextEpisodeFixSDK23.zip)

By the way, pull-to-refresh still works, well kind of... Pull up a bit, then pull down a lot and hold until it starts updating. It ain't pretty, but it works.

**Comment by casperklein** [comment]
Wow, that was a fast reply 🎉 

> [DroidShows_7.11.7_BiggerCovers270px+(canMark)NextEpisodeFixSDK23.zip](https://github.com/ltguillaume/droidshows/files/14376782/DroidShows_7.11.7_BiggerCovers270px%2B.canMark.NextEpisodeFixSDK23.zip)

This one works 👍 

> Pull up a bit, then pull down a lot and hold until it starts updating.

I tried it, but couldn't get it to work. But to be honest, I am not using that feature often. So doing it via the context menu is fine for me.

**Comment by ltguillaume** [comment]
Yeah I guess it could also depend on some other factors, but the trick is to get the circle fully visible. Let's just see it as an in-app minigame for now 😅

**Comment by casperklein** [comment]
Yeah, I love that kind of easter eggs 😆

I found a way on my device: pull up, then (really fast) pull down. Now the circle is fully visible but does nothing. Now release the finger (circle remains visible) and pull down one more time to start updating 🎉

**Comment by ltguillaume** [comment]
Yesss, you cheated the system! Anyway, maybe you're using those adaptive/colorized/themified icons from Android 14, haven't checked it yet, but it should work with the change in this release (according to the documentation I found): 
[DroidShows_7.11.7_BiggerCovers270px+(canMark)NextEpisodeFixSDK23MonochromeIcon.zip](https://github.com/ltguillaume/droidshows/files/14377534/DroidShows_7.11.7_BiggerCovers270px%2B.canMark.NextEpisodeFixSDK23MonochromeIcon.zip)

**Comment by casperklein** [comment]
I can't confirm that. It makes no difference on my device.

**Comment by ltguillaume** [comment]
What do you see vs. what do you expect to see? I've just tested it, works great! The background and foreground colors are defined by the OS, the old shadow is gone.

**Comment by casperklein** [comment]
Sorry, my mind was still connected to the in-app-game 🤣 For whatever reason, I thought this would also fix the pull-to-refresh issue.

**Comment by ltguillaume** [comment]
Yes, a better icon is a fix for everything 😉
