### ISSUE TITLE
[Translation] New version with two new strings

### ISSUE THREAD

**Issue by ltguillaume** [ltguillaume/droidshows#12]
@repetti and @helfio I've added two new strings and translated them myself with some searching and automated translation, could you please check if this is correct? The option is meant to hide (exclude) the shows without aired unseen episodes from the shows list. In English, I eventually settled for this:

```
<string name="menu_exclude_seen">Exclude seen</string>
<string name="menu_include_seen">Include seen</string>
```

Could you have a look at these translations for that:

German:

```
<string name="menu_exclude_seen">Gesehene verbergen</string>
<string name="menu_include_seen">Gesehene zeigen</string>
```

Spanish:

```
<string name="menu_include_seen">Ocultar vistos</string>
<string name="menu_exclude_seen">Mostrar vistos</string>
```

Russian:

```
<string name="menu_exclude_seen">Скрыть просмотренной</string>
<string name="menu_include_seen">Показать просмотренной</string>
```

**Comment by ghost** [comment]
Spanish translation is OK. No changes needed :)

**Comment by ltguillaume** [comment]
Thanks @helfio!!
This APK is a pre-release of v6.7 that includes a clean implementation of the "Include/Exclude seen" feature. It needs testing, especially when switching between sorting modes and between archived and current shows, and using the search. Again, Android is stupidly annoying with filtered lists... Please have a look if you find any strange behavior. You won't lose any data by it.

@repetti

**Comment by ltguillaume** [comment]
Ok, got the Russian translation via XDA. Just released version 6.7.

**Comment by ltguillaume** [comment]
I have one more string to be translated:

<string name="dialog_auto_backup">Automatically perform daily backups</string>

This is what I guessed for now.

German:
<string name="dialog_auto_backup">Automatische tägliche Datensicherung</string>

Spanish:
<string name="dialog_auto_backup">Copia de seguridad diaria automática</string>

Russian:
<string name="dialog_auto_backup">автоматическое ежедневное резервное копирование</string>

@helfio @repetti could you please correct the above strings? :)

**Comment by ghost** [comment]
Realizar copias de seguridad automáticas cada día

Would be perfect. If it's too long, your translation is easy to understand :)

**Comment by ltguillaume** [comment]
Yeah bit too long ;) so I'll keep it like this :) Thanks!

**Comment by ghost** [comment]
Thank you!

**Comment by ltguillaume** [comment]
@repetti @helfio 

I'd really appreciate it if people have a look at these uninformed sloppy translations I did:

English: _Long-press full-screen poster to open in external app_
German: **Lange antippen des Große Poster um in andere Apps anzuzeigen**
Spanish: **Deje pulsado el póster grande para abrir en otra app**
Russian: **Длинное нахатие на большой постер для просмотра в другом приложении**

English: _Edit seen date_
German: **Datum gesehen bearbeiten**
Spanish: **Editar Fecha visto**
Russian: **Изменение даты сим**

**Comment by ghost** [comment]
_Spanish_
1st one: Deje pulsado el póster a tamaño completo para abrirlo con otra app.
2nd one: Editar la fecha de visto.

I hope they're short enough :)

I'm not quite sure of the translation of the 1st one because I cannot figure out the context. I dropped Android and I'm not longer using the app, although I'm still happy to contribute :)

**Comment by ltguillaume** [comment]
Thanks! So where did you end up, iOS/Windows Phone/SailfishOS?

The text of the 1st item can be found in among the usage tips in the Options dialog. It means that if you go to the show details and click on the (small) poster, then you get the full-screen poster and on it you can long-press to open it in another app. Would it then be: _Deje pulsado el póster a pantalla completa para abrirlo con otra app_?

**Comment by ghost** [comment]
Yep, your translation is fine.

I ended in SailfishOS. I have a MotoG 1st edition and someone called Piggz made the port, so I'm enjoying it :)
I have to confess that I'm using other app to follow my TVShows but I miss yours :p

BTW It's nice that you have SFOS like one of the options.

**Comment by ltguillaume** [comment]
Ok, fixed the translation, thx! :)

Ah so cool! I'd love to try out SailfishOS, have been following it off and on, and if there were a possibility to try it on any of the phones lying around here, I would've definitely tried it already. That being said, I do think you should be able to run DroidShows just fine on SailfishOS! There aren't any strange dependencies, and I'm quite sure that a network connection and external storage access should be covered in SailfishOS's Android "VM wrapper". Check this out: https://jolla.zendesk.com/hc/en-us/articles/201440787-What-Android-apps-does-Jolla-support-and-how-do-I-get-them-

**Comment by ghost** [comment]
You can check for ports here: https://wiki.merproject.org/wiki/Adaptations/libhybris

Actually Android support it's not available for ports, so you must have an official handset to enjoy it :p
There is this SFdroid which is under development but still not ready, and in any case this just boot a whole Android inside SFSO and it's too much for Falcon hardware

**Comment by ltguillaume** [comment]
Yeah I know about that wiki, but I didn't know that the Android support is so limited and cumbersome, damn. I thought the implementation was a bit streamlined and integrated than just full-on virtualization. And since the current Jolla devices can hardly be classified as speedy beasts, I can imagine it's not such an attractive option.

**Comment by ltguillaume** [comment]
New strings, new translations! Please let me know if corrections should be made!

English (for reference):
<string name="menu_context_ext_resources">External resources</string>
<string name="dialog_show_next_airing">Show next airing instead of next episode\'s air date</string>
<string name="messages_next_airing">Next airing:</string>
\n&#187; Tap poster for next episode info
\n&#187; Double tap poster for external resource (to *[url]s directly, or list)
\n&#187; Long-press poster for show info
Use TheTVDB mirror (try if updates are too slow)

German:
<string name="menu_context_ext_resources">Externe Ressourcen</string>
<string name="dialog_show_next_airing">Zeige anstehende Lüften statt der nächsten Episode</string>
<string name="messages_next_airing">Nächste Ausstrahlung:</string>
\n&#187; Auf ein Poster tippen um Infos zur nächsten Episode anzuzeigen
\n&#187; Doppeltippen um Externe Ressource zu navigieren (direkt nach *[url]s, oder die Liste)
\n&#187; Lange antippen um Infos anzuzeigen
TheTVDB mirror verwenden (versuchen Sie dies, wenn Updates zu langsam gehen)

Spanish:
<string name="menu_context_ext_resources">Recursos externos</string>
<string name="dialog_show_next_airing">Mostrar la próxima emisión en lugar del próximo episodio</string>
<string name="messages_next_airing">Próxima emisión:</string>
\n&#187; Toque el póster para ver la información del próximo episodio
\n&#187; Doble toque para recurso externo (a *[url]s directamente, o lista)
\n&#187; Deje pulsado el póster para mostrar la información de la serie
Utilice TheTVDB mirror (intente si las actualizaciones van demasiado lento)

Russian:
<string name="menu_context_ext_resources">Внешние ресурсы</string>
<string name="dialog_show_next_airing">Показать предстоящую проветривание вместо следующего эпизода</string>
<string name="messages_next_airing">Cледующая трансляция:</string>
\n&#187; Нажмите на картинку чтобы для показа информации о следующей серии
\n&#187; Двойной кран для внешнего ресурса (к *[url]s непосредственно или список)
\n&#187; Длинное нахатие на постер показать подробности
Используйте TheTVDB зеркало (попробуйте, если обновления идут слишком медленно)

**Comment by ltguillaume** [comment]
@repetti @helfio please have a look! :)

**Comment by ghost** [comment]
Spanish translation looks great :)

**Comment by ltguillaume** [comment]
Thanks @helfio !!

Last thing, how would I translate the following:
"Use TheTVDB mirror (try if updates are too slow)"
Currently I have "Utilice TheTVDb mirror (intente si las actualizaciones van demasiado lento)"

**Comment by master-m1000** [comment]
@ItGuillaume I revised the german translation:
Externe Ressourcen
Zeige anstehende Ausstrahlung anstatt das Ausstrahlungsdatum der nächsten Episode
Nächste Ausstrahlung:
\n» Auf ein Poster tippen, um Infos zur nächsten Episode anzuzeigen
\n» Doppeltippen, um zur externen Ressource zu navigieren (direkt zu *[url]s, oder zur Liste)
\n» Lange antippen, um Infos anzuzeigen
TheTVDB mirror verwenden (versuchen Sie dies, wenn Updates zu lange dauern)

**Comment by ltguillaume** [comment]
Hi, thanks for your feedback! Since my request here, I've gotten some
feedback on the German translation via XDA, which resulted in the strings
used in v7.3.0. One of the most deviating translations is the use of
"Quelle" for resources (isn't Quelle more of a "natural resource"?). If you
haven't already seen v7.3.0, please have a look, but I'd be happy to change
the strings into your translations if you're saying these are better than
the current ;) np :)

**Comment by master-m1000** [comment]
F-Droid didn't show me the update. Seems to be a bug. The translation in v7.3.0 is fine.

The word resource exists also in german. Mostly it's used in the it jargon. But the app is for normal users, so it's better to stay at Quelle.
Little german course: If you mean the origin you can translate resource with Quelle, but if you mean goods you better say Rohstoffe. Or if you're lazy write the english word.

PS: This is the best app for tv series I saw. Keep it up!

**Comment by ltguillaume** [comment]
Thanks for the explanation and the big compliment :D

As for F-Droid, it's not a bug on their side, but there is always some
delay before it'll be available. As far as I understand it, after I create
a release on GitHub, some bot/crawler/spider by F-Droid picks up the new
release, then it's added to the queue of their compiler and eventually the
new version will be included in their database.

**Comment by ltguillaume** [comment]
@helfio I just received an updated Spanish translation, was wondering if you'd have a quick look at it to see if it actually improves upon the current translation or not. I've put the old and the new pull request next to each other for quick comparison (didn't work on github): http://www.diff-online.com/view/5871fbc7d249d

Thanks in advance!

**Comment by CalebCDE** [comment]
Sorry it was mine, using stringlate (A great mobile app)

My pull improve the treatment to user (more colloquial), fix some strings - fit the width with the labels -, and fix some genre strings (The spanish language, he and she... you know)

Kind regards!

**Comment by ltguillaume** [comment]
Thank you @CalebCDE !! Thanks for explaining the changes, obviously I have no knowledge of the language, so I thought I'd just ask someone else to have a peek at it, too :) Then I'll commit the changes. Thanks again! :)

Also, I'm receiving a suggestion from Eclipse to change "linea" into "línea", is this correct?

**Comment by ghost** [comment]
Yep, it's 'línea' :)

**Comment by CalebCDE** [comment]
YW @ltGuillaume ;)

**Comment by ltguillaume** [comment]
Ok, here's a test version with the new stings. Anything that needs changing @helfio @CalebCDE ?
[DroidShows_7.3.2esfr.zip](https://github.com/ltGuillaume/DroidShows/files/692106/DroidShows_7.3.2esfr.zip)

**Comment by ghost** [comment]
I hope @CalebCDE can test it. I have no android device around :p

**Comment by ltguillaume** [comment]
But the changes made as can be seen here http://www.diff-online.com/view/5871fbc7d249d (plus "línea") are all good then @helfio ? :)

**Comment by CalebCDE** [comment]
Hi! I cant install it

**Comment by ltguillaume** [comment]
I guess you're using the F-Droid release then? That one uses its on certificate to sign the apk. You'll have to backup your database via Options, then uninstall and install the version I posted above, then restore and update your database. Sorry, that's how these things go ;-)

**Comment by CalebCDE** [comment]
Yep, now ive tested, updated and finished :)

Pull created 👍 

Regards!

**Comment by ltguillaume** [comment]
Done! Released (and will be in F-Droid repo soon: it has to pick up the new release automatically and then it will be compiled for F-Droid).

**Comment by ltguillaume** [comment]
@amadeous @CalebCDE @helfio @repetti @casperklein

Hey! I need translations for 2 new features, of the following 4 strings:
- Pin
- Unpin
- Log
- Close log

Explanation: "Log" opens a log mode, which is a list of the latest episodes you have seen. "Close log" takes you back to the shows list. "Pin" allows you to pin a show to the top of the list, where it will remain until you "Unpin" it.

Machine translations are already included in the 7.4.0TEST version. For more info, have a look at https://forum.xda-developers.com/showpost.php?p=71118303&postcount=296

**Comment by ltguillaume** [comment]
@amadeous @CalebCDE @helfio @repetti @casperklein

**Comment by CalebCDE** [comment]
Roger! This weekend i can do it :))

**Comment by ltguillaume** [comment]
Thx :)) ;)

**Comment by amadeous** [comment]
I checked the french version and the new features and it seems good to me !
Nice updates ! Please let me know if I can help you with anything ;)

**Comment by amadeous** [comment]
I'm actually seeing a friend of mine who speaks italian tonight. I'll ask her if she could translate the app in italian.

**Comment by ltguillaume** [comment]
Wow, that would be awesome! Thank you so much! :)

**Comment by ghost** [comment]
Closest translation to Spanish that comes to my mind are:

pin -> anclar/fijar
unpin -> desanclar/soltar
log -> historial/registro
close log -> cerrar historial/registro

Anclar is the verb of use of an anchor, so it's a very similar meaning to pin. 
Fijar instead is more general and is directly translated to fix or attach.

Registro could work, but I think historial is more like in the mind of people, since is the word commonly used for browsing history.

I hope that helps :)

Edit: I tried to properly push my repo to yours, but I cannot find how to do it :-/
Anyway here you have :) [strings.txt](https://github.com/ltGuillaume/DroidShows/files/797420/strings.txt)

**Comment by ltguillaume** [comment]
Thanks @helfio! :) No worries, I'd rather enter those strings myself anyway, most of the times I want to correct something anyway, so a pull request is even more of a hassle ;)

So, now only **German** translations need to be checked before release.

**Comment by casperklein** [comment]
German translation:

pin = anheften
unpin = losheften
log = Protokoll
close log = Protokoll schließen
