### ISSUE TITLE
Unable to get info of Malcolm in the middle series

### ISSUE THREAD

**Issue by Ski-lleR** [ltguillaume/droidshows#17]
Hi,

I can get every series, except this one. I get an error "Error connecting to the thetvdb.com", while other series are scraped fine.

Same problem with DroidSeries.

Let me know if you need more info.

**Comment by ltguillaume** [comment]
Heya! What synopsis language are you using? I just added and then updated Malcolm In The Middle with English synopsis language without any problems.

**Comment by Ski-lleR** [comment]
That's fine now, maybe an error with my rom because i've reinstalled everything and scrape is ok for malcolm. Anyway thanks for the quick response and keep up the good work ;)
