### ISSUE TITLE
Serie not available in application

### ISSUE THREAD

**Issue by fantasio31** [ltguillaume/droidshows#18]
Hi,

I launched a search for "Dix pour cent" french show but nothing has been found in droidshows.

According to source code, application seems to execute a webservice query to TheTVDB database.
Using TheTVDB website, "Dix pour cent" has been found.

Maybe it's linked to "language" search parameter. It seems (not sure) to use the system language.
As my system language is "English" only "English" shows can be found.

Is there any way to change search show search language ?

**Comment by ltguillaume** [comment]
In the Options, change Synopsis language to Français and the series will show up.
