### ISSUE TITLE
Language specific details

### ISSUE THREAD

**Issue by Shadouw** [ltguillaume/droidshows#2]
Hi, this is not an issue but a feature request. 

TVDB provides series and episode details in different languages while DroidShows always pulls information in English. Is it possible to set another user preferred language in which the titles and details are pulled from TVDB and shown in the app? 
If preferred language is not available, English information as fallback would be nice.

**Comment by ltguillaume** [comment]
New release v5.5: Added option to change language for synopsis (= TheTVDb language code); Added popup list in show details to quickly search for actor on IMDb

**Comment by Shadouw** [comment]
This works great. Thank you very much.
