### ISSUE TITLE
& in episode title drops the rest of it

### ISSUE THREAD

**Issue by brunoicna** [ltguillaume/droidshows#23]
Hello,

I noticed that the episode 811 of Modern Family ("Sarge & Pea") is named just "Sarge" in DroidShows. Probably an issue with the ampersand :-)

Thank you for you app though, it's exactly what I need! :+1:  

Bruno

**Comment by ltguillaume** [comment]
You're right! I never fully rewrote the XML parsing code, and there was a problem with handling &amp; and other special characters. I think I found a neat and simple solution for it now and it allows for the removal of some workaround code, too. Plus it keeps spaces around these special characters. Have a look if everything's working for you with this test build.

https://github.com/ltGuillaume/DroidShows/releases/download/7.3.3/DroidShows_7.3.4.apk

**Comment by brunoicna** [comment]
Unfortunately, it doesn't seem to work any better on my device... Galaxy S5 with Android 6.0.1

**Comment by ltguillaume** [comment]
Have you updated the show?

**Comment by brunoicna** [comment]
Yes, twice.

**Comment by brunoicna** [comment]
Alright, removed and readded, everything works like a charm. Thanks a lot! (probably a connectivity problem earlier)

**Comment by ltguillaume** [comment]
Strange, I only had to update the show and it was corrected. (season 8 is the latest season, so it'll update regardless of your setting for "Update shows' latest seasons only").

**Comment by brunoicna** [comment]
Yes, I very strongly suspect a transient network problem, I don't see why it wouldn't work with just an update.
