### ISSUE TITLE
Encoding problem?

### ISSUE THREAD

**Issue by igoralmeida** [ltGuillaume/DroidShows#3]
As mentioned in #1 , some series have a unicode symbol <?> after the name. In a clean DroidShows installation, I can reproduce the problem adding, for example, "Start Trek: Voyager". A quick inspection of the database suggests it is only in the UI, since the series.serieName field has no other characters:

    sqlite> select serieName, length(serieName) from series;
    Star Trek: Voyager|18

**Comment by ltGuillaume** [comment]
This relates to the following change I made:
"Status of show in details, and † in overview if show is not continuing"

In other words, a unicode † "dagger" symbol is put behind a show that has ended. I used the dagger symbol  (U+2020), because it is very common, hence is present in practically all unicode fonts.

Do you use a custom font on your device?

**Comment by ltGuillaume** [comment]
Aah wait, something went wrong in the encoding of the source files somehow, you're right! I've now changed it in the code to " \u2020", so if it still won't work properly for you, it's got to be that you have some obscure font installed. But if you know of a similar character that is even more common, I can have a look at that.

**Comment by igoralmeida** [comment]
Well, it's a stripped-down version of OmniROM, so it shouldn't have anything obscure.

But shouldn't you increment android:versionCode? I don't think F-Droid will pick it up if it's the same number...

**Comment by ltGuillaume** [comment]
Shoot, forgot that again :P But I did that in the last update, and F-Droid hasn't checked for updates yet, so won't it just take the last commit tonight anyway?

**Comment by igoralmeida** [comment]
We can wait until tomorrow, but I suspect it won't. Otherwise, it would be a waste of resources to compile every single commit in upstream.

**Comment by ltGuillaume** [comment]
Say, currently, the versioncode is 13 (I never changed it until release on F-Droid :P).
Then, I made a new commit with versioncode 43. F-Droid hasn't picked up on it just yet.
Now, before F-Droid has compiled and released a new version with versioncode 43, I made another commit, still with 43 as versioncode.

Now, as soon as F-Droid checks for a new version, it'll check the latest commit only, I would say, which turns out has a different versioncode (43) from the previous compile (13), so it would compile a new version from the latest commit, not from the commit before that.

It would be really strange if anything else happened :P

**Comment by igoralmeida** [comment]
Ah, ok. I saw that 43 again and just assumed it would fail. Sorry for the noise.

**Comment by ltGuillaume** [comment]
No no, glad you're doing that! This distribution stuff is new to me, so I really do value your input!

**Comment by ltGuillaume** [comment]
I don't know what is going on at F-Droid, but it's supposed to compile the new version for two days now... If you still want to test it, make a backup from the Options dialog, uninstall the F-Droid signed APK and install + restore with this one: https://github.com/ltGuillaume/DroidShows/blob/master/apk/DroidShows_4.3.apk

This version is working for me, hope it solves the issue for you, too. After that, it's just waiting for F-Droid to start compiling (it's in the queue: https://gitlab.com/Jermey220900/fdroiddata/commits/master)

**Comment by igoralmeida** [comment]
Right, so I updated to version 4.3 and the problem still remains. Then, still in 4.3, I created a backup, hit Clear Data (via android's app settings), then restored from the backup, and the <?> symbol continues there.

The same happens if I clear the data once again and add a single dead show.

Also on the topic: the 'updating all shows' activity (the small one with a progress bar) seems to have a problem as well. The <?> unicode symbol shows up for *every* serieName, but this time immediately following the last letter (i.e. this looks like a \0 or \n, not a space-plus-dagger).

**Comment by igoralmeida** [comment]
http://imgur.com/38ztksR

**Comment by ltGuillaume** [comment]
Ok that's because F-Droid compiled the first new commit it found, not the
latest commit it could have found. The "..." is what you're talking about,
it used to work in non-F-Droid builds, but I'll change it asap. Thanks for
reporting!

**Comment by igoralmeida** [comment]
In retrospect, that makes a lot of sense. After all, F-Droid is supposed to show several versions of the app :)

I'll wait for the update and report back then.

**Comment by ltGuillaume** [comment]
Yep it's great that F-Droid allows you to backtrack a couple of versions if a bug in the newest version is crippling the app, for example :)

What I didn't know for sure was, when it detected a new versionCode and a new build "order" was added to the queue, whether the commit upon detection was compiled, OR whether it would compile the latest available commit as soon as the "order" was processed. I was guessing the latter to be the case, but the former was in fact what happened.

**Comment by ltGuillaume** [comment]
4.4 on F-Droid is on its way.

**Comment by ltGuillaume** [comment]
@igoralmeida F-Droid just updated DroidShows to 4.4 (FINALLY). Please have a look at the encoding problem for me :)

**Comment by igoralmeida** [comment]
Just updated, works fine. Thanks for fixing!
