### ISSUE TITLE
Lost list of current shows after newest update

### ISSUE THREAD

**Issue by nutpantz** [ltguillaume/droidshows#3]
Upgraded to the new version
(From the link on xda)

But now I can't see my current shows.. It says no shows found.
It's just blank black
If I add new shows they show up however.

They are there as when I ad show search I can see them starred.
I can't remove them and re ad them fun the ad show search

Archived list shows up fine.

**Comment by ltguillaume** [comment]
Hi, can you send me a backup of your database?

Doesn't really make sense: archived/not archived makes use of the same database field as enabled/disabled, so the transition should be smooth.

**Comment by nutpantz** [comment]
Where is the backup located?

**Comment by ltguillaume** [comment]
In the menu, choose Options and click the "Backup" button. Afterwards, you'll find DroidShows.db in the root of your SD-card.

**Comment by nutpantz** [comment]
Here you go

**Comment by ltguillaume** [comment]
You can only attach files of certain types on Github, so you can put the file here if you want: [link removed]

**Comment by nutpantz** [comment]
Its up

**Comment by ltguillaume** [comment]
Ah ok I see the problem. Don't worry, I'll fix it, you haven't lost anything.

**Comment by ltguillaume** [comment]
OK, fixed now!
Quite the Scooby-Doo fan you are ;)
