### ISSUE TITLE
Films and stuff

### ISSUE THREAD

**Issue by EdenDorf** [ltguillaume/droidshows#31]
Maybe you can add some section for Films that got seen?
The more i look so less i cant remember that. So i do waste less time.

Also it would nice to setup some notes on film's and series  or some favorites at them. Some parts of series that nice i would to look again in future. But then i can't remember wich it was.

Thanks for all the work done yet.

**Comment by ltguillaume** [comment]
I know the feeling. There is https://www.themoviedb.org/, of course, but I'm an avid fan of https://www.criticker.com. I'm still hoping they'll reopen their API someday, then I'll have a look into support for movies. In the meantime, you could just use the criticker.com website, also on mobile devices.

**Comment by ltguillaume** [comment]
Could you be more specific about the second request? How would you like to use this notes and favorites system exactly?

**Comment by EdenDorf** [comment]
Maybe some kinds of tags also. So get all episodes or series i tagged as SciFi by click on that tag. 

I would like to rate it how i like it (maybe with stars, always known) and i would like if i klick on "favorite" some episode of a series that it got shown on a submenu where all my special favorite's are.

Notes, mh like "this is annoying,  never look into it again " maybe notes could modified and viewed on top of a episode. And maybe set some kind of sign to clear out wich episodes have notes.

**Comment by Ibuprophen** [comment]
The following seems to have API info for the Criticker ltGuillaume. 

https://github.com/damienhaynes/TraktRater/tree/master/Sites/API/Criticker

Not sure if you were aware of this.

**Comment by ltguillaume** [comment]
Not sure if you checked what it actually does. It might _say_ CritickerAPI in the file name, but the code is only for converting an exported list of movies from Criticker into the format of Trakt.tv, that's all it does.

**Comment by Ibuprophen** [comment]
I knew that... LOL!!

I thought that it would be something interesting for you to modify for the DroidShows app. 

Only a helpful suggestion my friend :-)

**Comment by ltguillaume** [comment]
Well, then it's not an API, so I can't help anyone with that, but apparently you already knew that then :-P

**Comment by Ibuprophen** [comment]
I'm curious about this issue report remaining open... 

Is this regarding a feature to be implemented in the future? 

Just wondering.

**Comment by ltguillaume** [comment]
If Criticker would get a new API, yes.

**Comment by Ibuprophen** [comment]
Anything new on Criticker releasing any new API's?

**Comment by ltguillaume** [comment]
Nope, but I'll keep checking.
