### ISSUE TITLE
New UI

### ISSUE THREAD

**Issue by Jiack214** [ltguillaume/droidshows#36]
Have you considered to redesign this app?
I like it so much but I think it's ugly  😕

**Comment by ltguillaume** [comment]
Thanks for the compliment. Yes I have, on multiple occasions but I'm not gonna. It's functional, and tweaked to the pixel. Plus, I'm starting to hate Android (well, Google) so much that I'm not inclined to put much effort into revamping DroidShows. It'll stay functional and I'll add a feature or two here and there, and that's that.

**Comment by ltguillaume** [comment]
@Jiack214 How about this?

[DroidShows_7.7.0BETA.zip](https://github.com/ltGuillaume/DroidShows/files/1348191/DroidShows_7.7.0BETA.zip)

**Comment by ltguillaume** [comment]
@Jiack214 @casperklein @ibuprophen1 @helfio Updated

[DroidShows_7.7.0BETA2.zip](https://github.com/ltGuillaume/DroidShows/files/1350811/DroidShows_7.7.0BETA2.zip)

**Comment by ltguillaume** [comment]
![ds7 7-1](https://user-images.githubusercontent.com/4777345/31105523-23c01928-a7e5-11e7-95a5-62b1000a9a39.png)
![ds7 7-2](https://user-images.githubusercontent.com/4777345/31105525-23c1b06c-a7e5-11e7-91d9-8f6783ad2872.png)
![ds7 7-3](https://user-images.githubusercontent.com/4777345/31105524-23c08b24-a7e5-11e7-97f3-2594c3986f15.png)
![ds7 7-4](https://user-images.githubusercontent.com/4777345/31105522-23be3644-a7e5-11e7-9629-2e007ca3e088.png)
![ds7 7-5](https://user-images.githubusercontent.com/4777345/31105526-23c401e6-a7e5-11e7-9021-31eb52a354f3.png)

**Comment by casperklein** [comment]
I really like the GUI improvements 😃

But in difference to your Screenshots, my top-bar is white (which does not look good imho + the three dots on the right are practically invisible).

![screenshot_20171004-182141](https://user-images.githubusercontent.com/590174/31187116-1f1982d6-a931-11e7-83b3-1a4607ef0fe7.png)

**Comment by casperklein** [comment]
I just installed the final release. It's already fixed there. Sorry for the noise.

**Comment by ltguillaume** [comment]
Yeah, I got this report earlier, so fixed it soon after. Sorry, should have mentioned it here.
