### ISSUE TITLE
New Context Menu Feature Is Too Dark... 

### ISSUE THREAD

**Issue by Ibuprophen** [ltguillaume/droidshows#37]
As great as those alternative options are to access... It literally took me about about 15 minutes to find it LMAO!!! 

The 3 sandwich like dots to the right was also as dark as the rest, any darker would make it, pretty much, invisible. :what: 

HA-HA!!! 

I'm never making fun of you, nor of the improved feature but, i felt like I was going out of my mind trying to locate them. :eek: 

It's not an emergency but, can you please keep in mind, inclusive with your next release, to lighten up the color a bit for the context menu option on the shows and seasons list? 

That would be great! 

Thank you very much my friend. 

2 Screenshot Examples have been provided too. 

This first one reflects the List of Shows... 

![1-shows-list-example](https://user-images.githubusercontent.com/18060271/30089765-ce3e2670-927c-11e7-806f-c8134b07d397.jpg)

This second one reflects the List of Episodes... 

![2-seasons-list-example](https://user-images.githubusercontent.com/18060271/30089774-d4c414c8-927c-11e7-8ca3-17efa6225edd.jpg)

**Comment by ltguillaume** [comment]
Heya! Thanks for checking out the new thingy. II just copied over the three-dot icon from the Android SDK, and at first I thought of it exactly like you did: it's a bit obscure. Then, when I changed the PNG to the lighter one (like the default one in the action bar above), I saw that it was far too intrusive and really ugly to have a button like that "stick out" in every row. So, I decided to keep it this way. The only thing I'll do is mention its presence in the descriptions in-app and on the website. Once you know it's there, you don't even really need a visual queue anymore, and I still think the icon currently is obvious enough, but blends in nicely.
