### ISSUE TITLE
Feature request: Make keyboard automatically appear when using the search function

### ISSUE THREAD

**Issue by casperklein** [ltguillaume/droidshows#38]
I've a little feature request: When I use the search function, the textbox appears and I can search. But I have to tap it first, to make my keyboard appear. Would be nice, if that could be automatically be done.

Thank you!

**Comment by ltguillaume** [comment]
Yeah I didn't see this because it still worked when I used the hardware search button on my device. But it'll be fixed in the next version. Thanks for reporting!

**Comment by Ibuprophen** [comment]
This is not a big deal for me but, i'm not a big fan of this feature.

If it's implemented... then it's not a big deal for me. :-)

**Comment by ltguillaume** [comment]
There's no reason NOT to open the keyboard when you want to search for a show, is there? :P

**Comment by Ibuprophen** [comment]
No reason at all. It's only a personal preference that I'm not a fan of but, if it's implemented, then it's not a big deal with me as long as the app works LOL.

**Comment by ltguillaume** [comment]
Should be working now: https://github.com/ltGuillaume/DroidShows/releases/tag/7.6.2

**Comment by Ibuprophen** [comment]
No issues to report here. 

The search function defaults the cursor to the search text with the keyboard available to begin typing. 

Excellent work!

**Comment by casperklein** [comment]
@ltGuillaume
This feature is broken for me. I am not sure, but I think it's since I've updated to Android 12 recently.
I am using the latest DroidShows version 7.11.2. Could you take a look? If you need further information or want me to open a separate issue, just let me know.

**Comment by ltguillaume** [comment]
I'm on 10 and 11, so I'll need your help testing, but I'll have a look, yeah.

**Comment by ltguillaume** [comment]
@casperklein So for you, the keyboard _doesn't_ show up, right? For now I could only find something about the keyboard reappearing when it shouldn't since Android 12 (https://github.com/mozilla-mobile/android-components/issues/11252), not the other way around.

**Comment by casperklein** [comment]
Yes. The cursor is blinking in the search field, then I have to tap on it to get the keyboard appear. Just like before you implemented this back then.

**Comment by ltguillaume** [comment]
Could you have a look if this version works @casperklein?
[DroidShows_7.11.3_Android12KeyboardFix.zip](https://github.com/ltGuillaume/DroidShows/files/7876339/DroidShows_7.11.3_Android12KeyboardFix.zip)

**Comment by casperklein** [comment]
Nice, this works. Thank you 😄

**Comment by casperklein** [comment]
PS: I noticed another regression, which really has no urge to be fixed for me. In the TV show list, the "pull-down to update the TV shows" feature isn't working. However, via the context menu (three dots on the right), the same feature works. So it's just the gesture, that stopped working.
I know, that fixing things you can't test yourself is not that easy. Shall I open a separate issue as reminder?

**Comment by ltguillaume** [comment]
Keyboard popping up probably still doesn't work when opening the external resources editor, but I don't think it's a big problem there.

Yes, please create a separate issue, perhaps I'll be able to have a look at it with someone else's phone soon.
