### ISSUE TITLE
The return of: Context menu opens mostly below visible area

### ISSUE THREAD

**Issue by casperklein** [ltguillaume/droidshows#39]
Version 7.6.1

Almost same issue as in: https://github.com/ltGuillaume/DroidShows/issues/35

But in addition to the scrollable context menu with an "empty" row on top (just figured out, its not empty, but contains the tv show title with an estimate font size of 1px).

![screenshot_20170922-194657](https://user-images.githubusercontent.com/590174/30757490-304c5e86-9fcf-11e7-8eef-e70600a41099.png)

**Comment by Ibuprophen** [comment]
Okay... I'm just throwing out an idea thinking outside the box... 

What is your devices "LCD Density" (aka the devices DPI) set to? 

Mine is set on "480 DPI (default)". 

I was just thinking about this off the top of my head. 

Thanks!

**Comment by casperklein** [comment]
I am not completely sure what you mean.  My screen resolution is 2560x1440.

Hope that helps: https://pixensity.com/list/samsung-galaxy-s7-8455/

**Comment by casperklein** [comment]
I noticed, if I use the three dots on the right to open the context menu, it opens correctly.

The issue happens only, when I long tap a tv show to open the context menu.

**Comment by Ibuprophen** [comment]
Your devices screen resolution capability is different than the devices current DPI setting... 
I think I had lost you with that... 

Though you were able to use the 3 Dots for the menu, you shouldn't need to compensate one function that's working correctly for another function that's not working correctly. 

What was the last version of the app when that long press function was working correctly?

**Comment by ltguillaume** [comment]
Strange stuff. I'm using default Android framework widgets, but still the context menu header and the position somehow suck on your device. I'd say Samsung messed up, but I still should get it working on such a common device, so I'll look into it after I get the new TheTVDB API working.

Just please confirm that you're not using a custom ROM or anything like Xposed Framework or theming stuff to change Android's appearance.

**Comment by casperklein** [comment]
It's not a big issue for me, I just wanted to notify you about it. Take your time and thank you for looking into it.

I am using the latest stock ROM (Android 7.0, not rooted, not customized in any form).

**Comment by Ibuprophen** [comment]
The DroidShows works without any issues on both my Samsung S3 & S5. Both has a Custom ROM and XPosed.

I was just thinking that it may be a lower set resolution/DPI than the typical default 480 DPI but, i'm not 100% that this is the case.

**Comment by ltguillaume** [comment]
Nah, it's just because Samsung or Google screwed up the framework resources.

**Comment by ltguillaume** [comment]
Ok, here's a bug fix release that works around these Android issues: https://github.com/ltGuillaume/DroidShows/releases/tag/7.6.2

**Comment by Ibuprophen** [comment]
I just wanted to state that I do love that "Android Sucks" Label you used... LMAO!!! 

It looks like something an Apple user would have created... HA-HA!!!

:-)
