### ISSUE TITLE
feature request: dashboard view showing upcoming air dates instead of show list

### ISSUE THREAD

**Issue by mdaniel** [ltGuillaume/DroidShows#4]
When I open DroidShows, I don't need to see the list of shows rather I need to see the list of air dates that are coming up for the shows I have chosen. It seems like the tiny text on line 3 of the show row kind of gets there, but it is tiny and seems to want me to watch every episode I have not yet seen, which doesn't help me this week.

Specifically:
```
for each show:
    for each episode in that show in desc order by air date:
        if episode.air_date between today - 7d and today + 7d:
            add episode to welcome screen
```
The thinking of the `today - 7d` is that you may have missed an episode's original air date, but it could still be online.

**Comment by ltGuillaume** [comment]
Hi, thanks for sharing your thoughts! I'm afraid that DroidShows has a bit of a different point of view on this: imho, a dashboard is just another screen to keep you from where you wanna go eventually. The shows list is intended to give you all the information you need in one glance, plus direct shortcuts to both show info (tap poster), seasons (tap row) and even IMDb details (long-press poster). Its sorting is to accommodate for binge watching: sort by number of unseen aired episodes, then by date of first aired.

You get to see immediately if there are new episodes aired by means of the text color. As said, the shows with no new aired episodes are sorted by the date a new episode comes out. This should give a good overview, one that a welcome screen won't exactly improve on I think.

Concerning the text size,on the screens of the phones and tablets I have tested it on the text size was a good balance between readability and screen economics. May I ask what kind of screen you're using (size and resolution)?
