### ISSUE TITLE
Found something accidentally for the pull down update feature... 

### ISSUE THREAD

**Issue by Ibuprophen** [ltguillaume/droidshows#40]
This was found by accident... LMAO!

While on the main screen of the app, take your finger (anywhere) and do a fast flick down (a really fast pull down) and the app will perform an update. 

I hope i had explained it okay via text... LOL! 

It's not a bad thing but, I thought that i would just bring it to your attention. 

Thank you!

**Comment by ltguillaume** [comment]
Are you sure you're using the official release? There have been several beta versions of 7.6.1.

**Comment by Ibuprophen** [comment]
I had downloaded the one off Github when I had redone my device.

**Comment by ltguillaume** [comment]
This could theoretically only happen if you pull down the list completely twice and there happens to be exactly 1000msec between those two incidents. Otherwise it'll only refresh when you pull down and wait for a second.

**Comment by Ibuprophen** [comment]
It's not a big problem with me since I accidentally ran into it. I'll live with it :-) 

Maybe as a feature request for a future release is to add another box in the options to be able to turn on/off the pull down update feature. 

Just a suggestion... :-)

**Comment by Ibuprophen** [comment]
I'm thinking that this should be a closed issue, based on the response from ltGuillaume, that this is not actually an issue but, it supposed to do this by design. 

Thank you very much! :-)
