### ISSUE TITLE
Issues Confirmed When Restoring DroidShows Backup DB... 

### ISSUE THREAD

**Issue by Ibuprophen** [ltguillaume/droidshows#41]
I just wanted to confirm the reporting regarding that restoring the DroidShows Backup DB returns multiple errors reflected in the attached Logcat and DB. 

This is for the record reflecting the issue and, after checking TheTVDB forum, the api v1 is still up and is still not scheduled to be taken down till 01-Oct-2017.

Please advise... 
[DroidShows.zip](https://github.com/ltGuillaume/DroidShows/files/1331750/DroidShows.zip)

[screenshot_20170925-234404](https://user-images.githubusercontent.com/18060271/30841720-dce9e572-a24b-11e7-998f-0c18532a744c.png)

**Comment by Ibuprophen** [comment]
I apologize for not clarifying this so I'm just going to add here what i had entered in the XDA Thread. 

This is exactly what I had done: 

1) Backed up the DB folder.
2) Uninstalled the app. 
3) Deleted the db file from the app folder (not the backup one). 
4) Reboot the device. 
5) Reinstalled the app. 
6) Opened up the app to confirm that it reflects a fresh install then closed the app. 
7) Copied the backup DB folder to the apps backup location. 
8) Opened up the Logcat app and applied the "per app" filter. 
9) Opened the DroidShows app and performed a restore with no errors reported from DroidShows itself. 
10) After confirming the issue reported on the thread, i had performed a backup in the app, took a screenshot and closed the app. 
11) Went back into the Logcat app and saved the Logcat results to a text file. 
12) Placed all the saved information, zipped them all up and created an issue in Github and uploaded everything for you. 

I also had went to TheTVDB forum to see if any announcements were made and/or amended. No changes, thus far, and the same 01-Oct-2017 date remained. 

In addition, if the API v1 was taken offline, then the DroidShows app should have reflected this as an error on the top of the device to the left of the clock area but, it didn't. As you can see from the screenshot, i had provided in Github, there were no app notifications. 

All the information was as accurate as possible.

Thank you very much! :D

**Comment by ltguillaume** [comment]
All right, thanks for the elaborate post. So, what I need to do is the following:
1) The URLs to the posters have been changed. I'll update that for the next version which will support the new API.
2) DroidShows still uses a bit of legacy code for the poster downloading. I'll add some more error handling.

**Comment by Ibuprophen** [comment]
Just announced on TheTVDB forum:

"Due to some delays getting the new site schema in place, we're suspending the sunset date for the old API. You should still move over the the new API as soon as possible but we are aware there are some outstanding usability concerns that can't be addressed just yet. Our apologies for the delay, we will update again when we have solid dates."

I had a feeling that this was going to be delayed based on the Forum activity.

**Comment by ltguillaume** [comment]
Great! Then here's the bug fix release without APIv2 implementation: https://github.com/ltGuillaume/DroidShows/releases/tag/7.6.2

**Comment by Ibuprophen** [comment]
The new release is working great! 

I performed the same fresh install procedure as listed previously with the new release and no issues to report. 

In fact, this release ran much more smoothly and much faster too. 

Thank you very much for your time, patience and understanding!
