### ISSUE TITLE
Feature request/suggestion: Combine Search & Add tv show

### ISSUE THREAD

**Issue by casperklein** [ltguillaume/droidshows#44]
I searched for a tv show and got an empty result list, because the show was not added before (works as designed). 

To add more comfort adding tv shows I suggest the following:

When searching for a tv show that has not been added, a empty result list is shown. To easily add the tv show it would be nice, if there could be a button or something to automatically open the "add tv show" menu with prefilled search term (and maybe execute the search). That way, the tv show has not to be typed in again.

I know the comfort gain is not that much. So consider this request only, if it's not to hard to implement :)

**Comment by ltguillaume** [comment]
There ya go.
[DroidShows_7.7.2.zip](https://github.com/ltGuillaume/DroidShows/files/1379181/DroidShows_7.7.2.zip)

**Comment by casperklein** [comment]
Works! Thank you :)
