### ISSUE TITLE
Notifications for new episodes?

### ISSUE THREAD

**Issue by guihkx** [ltguillaume/droidshows#45]
Hey, I was wondering if you plan to implement notifications for new episodes? I think it'd be a great feature.

Thank you for this app!

**Comment by ltguillaume** [comment]
Nope! It's been asked before, but I don't want this app to be intrusive at all. There are online calendars for that, so you can integrate this in your calendar app. Plus, the air times on TheTVDB don't specify the timezone, so it'll be off a few hours on more than a few occasions. Have a look at https://play.google.com/store/apps/details?id=usa.jersey.tvlistings or something.

**Comment by guihkx** [comment]
While I disagree with your reasoning, I do understand your point. I was using TV Time on my previous phone, but now I got a new one and I decided to use it without Google Services. Plus, I'm trying to use as much FOSS apps as possible, and DroidShows is good enough for me, so thank you!

Although an opt-in notification system would be much appreciated... :hear_no_evil:

**Comment by Ibuprophen** [comment]
I do completely agree with itGuillaume... 

I feel, personally, that the "Prime Directive" (just a little Star Trek pun LOL!) of this app is to track the shows/episodes that you've seen while keeping an eye on the show/episode that's to be aired. 

The bonus features is the ability to obtain any additional information regarding the show/episode with links to the IMDB for even more information. 

I feel, personally, that the Notification feature would, in fact, be both intrusive and misleading. The episodes in the app does have information on the date it airs but, it may be different for other regions, channels, and, in some cases, even dates without the time. 

The link that itGuillaume had provided is to an app that i even use that's a TV Guide app that has everything needed for notifications as well as other customizations for this specific purpose. 

I hope i had explained this okay via text... :-)
