### ISSUE TITLE
ux: clicking DroidShows on search results screen should return to the main screen

### ISSUE THREAD

**Issue by mdaniel** [ltGuillaume/DroidShows#5]
It is traditional that the icon and label in the upper left takes one to the screen that the label contains, but the icon/label on this screen does not.

To reproduce:

1. Tap the 3-dot icon
1. Choose Add a show
1. Type Robot Chicken and press Go
1. Tap the DroidShows label
1. Observe that nothing happens

**Comment by ltGuillaume** [comment]
DroidShows is all about minimalism and compatibility. The title bar with its icon, however, are sort of a compromise between the two: it consists of a hack
<uses-sdk android:minSdkVersion="9" android:targetSdkVersion="11"/>
to show the menu overflow button on Android versions above 2.x, nothing more. Implementing a toolbar that does the same would mean integrating a whole action bar library such as Sherlock, only to reach this goal. That thing is already 3 times as big as DroidShows itself, so I don't think it's a viable option. Furthermore, you can go back not only by using the back button of your device, but also by using the left-to-right gesture (or right-to-left if you choose so in the options).
