### ISSUE TITLE
Feature request: make it easier to find and add shows in different languages.

### ISSUE THREAD

**Issue by Zegnat** [ltguillaume/droidshows#50]
Here is another one. I have at times had a hard time adding certain shows, maybe because of how DroidShows searches.

E.g. I did not get a hit on “Les petits meurtres” (for <i>Les Petits Meurtres d’Agatha Christie</i>). But it does give me a hit [on the database site](https://www.thetvdb.com/?string=Les+Petits+Meurtres&tab=listseries&function=Search). Finding the English name of the series (through [Wikipedia](https://en.wikipedia.org/wiki/Les_Petits_Meurtres_d'Agatha_Christie)) did let me add it. One I still haven’t been able to add is “De Slimste Mens”. Again no problem [finding it on TheTVDB](https://www.thetvdb.com/?string=de+slimste+mens&tab=listseries&function=Search) at all. This one does not have an English name (that I could find) to try instead…

If DroidShows’ offline search can’t be as wide as the online one, maybe for performance reasons or because you aren’t storing show names in all possible languages, that is understandable. But then try and offer a fallback for the less obvious shows.

One possible fallback could be if DroidShows allowed me to add shows by their TheTVDB Show ID. That way people have a way to always add it to the app if they can find it on TheTVDB no matter under what name.

**Comment by ltguillaume** [comment]
Try "The Smartest Man". I will have a look at the search API, but this
primarily is a TheTVDB problem.

**Comment by Zegnat** [comment]
> I will have a look at the search API, but this primarily is a TheTVDB problem.

So searching through their API does not match searching through their website?

**Comment by Zegnat** [comment]
Ah. This is probably caused by DroidShows [limiting its searching](https://github.com/ltGuillaume/DroidShows/blob/5729ef30d9ad19cd6c4807ceb5b8f105931c245e/src/nl/asymmetrics/droidshows/ui/AddSerie.java#L136) to the current `DroidShows.langCode`. So because my Android is set to English, that’s what the API is limiting the searching to.

So shows that really don’t have official English titles (like “The Smartest Man”…) that have translated titles on TheTVDB are only findable under that name.

I would’ve expected DroidShows to use `all` as language for the [GetSeries](https://www.thetvdb.com/wiki/index.php?title=API:GetSeries) API call.

**Comment by ltguillaume** [comment]
Yeah I figured as much, but I won't change it. Without a language code in the search command, you'll a list with all results of all languages, thus up to 20x the same show.

If you really can't find the show, and you know it's - for example - Dutch, just change the synopsis language to Dutch and search for the show. You can change the synopsis language back to English later on.

**Comment by Zegnat** [comment]
I have had a go at implementing the v2 API and it doesn’t even (currently) allow an `all` language search. So going forward there is no good solution, even if we would build some clever de-duping of results.

Maybe there is some value in doing what the Wikipedia app does instead, and offer a clear language picker UI on the search field? It wasn’t clear to me at first that “synopsis language” in the options menu affected search.

This is how searching for <i>De Slimste Mens</i> works in the Wikipedia application, note how the UI clearly shows the language the user is searching in right now:

![Side-by-side comparison screenshots of the Wikipedia Beta for Android application, showing the search results for “De Slimste Mens” on English and Dutch Wikipedia.](https://user-images.githubusercontent.com/490579/34354673-404ab822-ea30-11e7-9b7b-e16ec52393da.png)

**Comment by Ibuprophen** [comment]
The DroidShows in my device is set for the English Language and I had performed a search using only the word "Slimste" and I believe that it had located it as reflected on the 2 attached screenshots. 

[sample1](https://user-images.githubusercontent.com/18060271/36635484-8057f272-1983-11e8-93fd-e9d86fb5a03f.jpg)

[sample2](https://user-images.githubusercontent.com/18060271/36635486-8aa4ff0e-1983-11e8-8641-749db25e0816.jpg)

I just performed a search using only the word "meurtres" and received a result as reflected on the following 2 attachments. 

[sample3](https://user-images.githubusercontent.com/18060271/36635517-72f279ee-1984-11e8-83e5-c20b57576b78.jpg)

[sample4](https://user-images.githubusercontent.com/18060271/36635520-7c3442b2-1984-11e8-81a0-2ed9309472cb.jpg)

**Comment by Zegnat** [comment]
I’m afraid those are completely unrelated shows. What I think is happening there is that those shows do not have an English title in the database at all, and therefore the API will find them when matching a Dutch and French word respectively.

**Comment by ltGuillaume** [comment]
Switching between languages is now possible (context menu). If there is no info available for that language, it will show the English info, but it still sets the preferred language. If someone decides to enter the localized info into TheTVDB, it should show up after updating.
[DroidShows_7.7.3.zip](https://github.com/ltGuillaume/DroidShows/files/1868550/DroidShows_7.7.3.zip)

**Comment by ltguillaume** [comment]
Choose language when adding a show. Once added, a show's language will be kept even when changing the default synopsis language in Options. Switching between languages is also possible (context menu). If there is no info available for that language, it will show the English info, but it still sets the preferred language. If someone decides to enter the localized info into TheTVDB, it should show up after updating. Also allows you to search in ALL languages and shows language behind search results.
[DroidShows_7.7.3.zip](https://github.com/ltGuillaume/DroidShows/files/1868721/DroidShows_7.7.3.zip)

@Zegnat have a look! ;-)

**Comment by Ibuprophen** [comment]
@ltGuillaume... 

I tested it out and... 

At first guess i figured out what to select to open the language menu but, just a suggestion, can you add something like "select here to change"?

[That may be a bit too long but, something to indicate that selecting that language bar will open the menu.] 

First off... After changing the language to a few of the options available, it does reflect the selected language within the language bar (like [ES] when I selected Spanish/Espanola). 

Unfortunately the language did not change. I selected to backup, exit then reopened the app and the language remained in English though the language bar did reflect the language I had selected.  

Here's some quick screenshots I had made to hopefully help. Please let me know if you need any further information :-) . 

[screenshot_20180402-143520](https://user-images.githubusercontent.com/18060271/38210605-e3326e62-3685-11e8-98fa-8cef0ee45dd4.png)
[screenshot_20180402-143511](https://user-images.githubusercontent.com/18060271/38210626-f30a9a26-3685-11e8-9071-74f6d4a6fec8.png)
[screenshot_20180402-145728](https://user-images.githubusercontent.com/18060271/38210753-4ba8830a-3686-11e8-82b3-eaa8022255ea.png)
[screenshot_20180402-145742](https://user-images.githubusercontent.com/18060271/38210771-585a8c74-3686-11e8-82a4-24203b467e70.png)

These screenshots reflect English but, it supposed to be in Spanish... 

~Ibuprophen

**Comment by ltguillaume** [comment]
My goal is to allow people to choose the synopsis language for shows individually.

1. The "Synopsis language" button in the options dialog only changes the default language for when adding a new show. It is also used for Wikipedia look-ups. Simply changing that one doesn't update the shows, nor does it change the language for any existing show. By design.
2. As I said, you can change the synopsis language per-show (very handy) via the context menu
3. While adding a new show, you can filter the shown synopsis languages (or even choose "All")

**Comment by Ibuprophen** [comment]
My deepest apologies! 

I had, slightly, misunderstood the information and thanks for pointing this out. :) 

I'll give it another shot... :)

**Comment by Ibuprophen** [comment]
I had tested this again per the outline by @ltGuillaume. 

It does work but, I don't know if someone noticed this or if it's just me but, try the following steps and see. 

1) In the options, select "All" for language preference. 
2) Search for a word that would result in a bunch of languages. I used "Beatles" and "Aliens". Then take a quick look at the results but, don't leave that Search Result Screen. 
3) Afterwards, go to the top of the search results screen and change the language to another language (one of the ones stated in the results) and the list should refresh to display the results for that language only and take a quick look at the results. 
4) Go back to the top and select "All" languages again and look at the results again. 

Though, this happens about half of the time  but, the results slightly differs from the original "All" language search, then the specified language and then back to the "All" language. 

Please don't get me wrong. I'm not stating that all will be changed but, one or more of the results differ between the 1st, 2nd and back to the 1st. 

The results from the 1st should match the 3rd and the 2nd should have only that specified language listed other 2 has. 

I hope that I had explained this okay via text... 

It's a slight change in results with a simple change of language within the search results. The steps look complicated but, it's simple with my outlining what and where. 

I'm going to try to get a few screenshots together to help visually but, this is a slight challenge... LMAO! 

~Ibuprophen

**Comment by ltguillaume** [comment]
Sorry I can't reproduce. I've tried with the exact same terms you used. Could it be that the order is different, but the results stay the same? Either way, it should be something related to the TheTVDB API, not to how DroidShows asks for or handles the results.

**Comment by Ibuprophen** [comment]
Not a problem then. 

I don't use this feature but, if anything arises from someone who uses this feature then I'll do my best to help you out with this. 

It is an impressive feature too! :-)
