### ISSUE TITLE
Enhancement request: Set permanent backup/restore location

### ISSUE THREAD

**Issue by source124** [ltguillaume/droidshows#53]
Hi :)

Thank you for the ability to choose a different location for backup/restore, and it would be better if it can be set to automatically use that location in the future.

Thanks

**Comment by ltguillaume** [comment]
Will do. Sorry I haven't found the time for an update lately.

**Comment by source124** [comment]
Thanks (and thanks for your effort)!

**Comment by ltGuillaume** [comment]
@source124 Please try this.
[DroidShows_7.7.4.zip](https://github.com/ltGuillaume/DroidShows/files/1881145/DroidShows_7.7.4.zip)

**Comment by ltguillaume** [comment]
@source124 Please try this.
[DroidShows_7.7.4.zip](https://github.com/ltGuillaume/DroidShows/files/1881195/DroidShows_7.7.4.zip)

**Comment by source124** [comment]
Thanks! It is good to see you working on the app. When can we expect a new (official) release?

**Comment by ltguillaume** [comment]
Still looking into (permanent) backup onto external sd card. Got... to...
get it... working (without including the Android support library)
