### ISSUE TITLE
Difficulty finding and adding shows with generic or often used title?

### ISSUE THREAD

**Issue by ghost** [ltguillaume/droidshows#56]
I want to thank the developers for a terrific and convenient app, this makes tracking all my (possibly excessive) TV watching so much easier. The single problem I've encountered was trying to add a recent show that has a nonspecific title (*Taboo*, 2017) which only resulted in two hits, none of them correct.

Whether this is specific to that one show or relates to the fact that the title is pretty nondescript I don't know – on the other hand, the intended result ranks in the top five on both IMDb and TheTVDb where I assumed the app pulls its searches from.

I'm kind of stumped what causes this, hopefully someone can clear this up and – best case scenario – iron out the bug?

**Comment by ltguillaume** [comment]
I know, the search API isn't the best. Might be improved with TheTVDB's new
API. I just tried "Taboo (2017)" (without quotes) and found the show. Good
luck!

**Comment by ghost** [comment]
Good to know, thanks for the quick reply! I'm fine with less than perfect search functions if I know to input more exact queries.
