### ISSUE TITLE
Popup Message When Updating Shows... 

### ISSUE THREAD

**Issue by Ibuprophen** [ltguillaume/droidshows#57]
Hello Again @ltGuillaume 

I do understand the purpose/reason behind the Popup message (example image attached) when the option to update all shows are being used via the top right menu selection... 

[example](https://user-images.githubusercontent.com/18060271/39202842-291bf942-47c1-11e8-944a-963a42e0ba37.jpg)

... I'm just wondering why that Popup isn't displayed when the pull-down feature is used as well? 

I wasn't sure if this was by design or just a minor oversight. 

Thank you very much! :-) 

~Ibuprophen

**Comment by ltguillaume** [comment]
By design. The pull-down already has visual feedback: you won't choose it by accident. That is (more) possible when using the menu.

**Comment by Ibuprophen** [comment]
I see... 

The popup provided when the selection, via the menu was made, is just an FYI in case it was made in error. 

The pull-down doesn't have the popup because the pull-down is considered an intended action since it requires the pull-down update to be held there. 

Am I correct? 


~Ibuprophen

**Comment by ltguillaume** [comment]
Plus it informs if you can still speed up the process.

**Comment by Ibuprophen** [comment]
Exactly what I was just thinking... 

The process would be quicker regarding the toggling of the process of "updating only the current season" as opposed to the "whole kit and kaboodle" (everything for the shows). 

Thank you very much for your time and understanding with my questions @ltGuillaume!!! :-) 


~Ibuprophen
