### ISSUE TITLE
Understanding the Backup Files... 

### ISSUE THREAD

**Issue by Ibuprophen** [ltguillaume/droidshows#58]
Hello Again @ltGuillaume 

I'm just wondering what the reasoning behind the need for the 3 backup files... 

DroidShows.db 
DroidShows.db0
DroidShows.db1

... when everything is within the DroidShows.db file. 

If I was to install the app as a fresh install and delete all but, the DroidShows.db file, then perform a restore with only that 1 file, everything would restore fine as well as exactly the same if I were to restore while having all 3 files. 

I'm just curious about this... :-) 

Thank you very much! 

~Ibuprophen

**Comment by ltGuillaume** [comment]
Have you had a look at the dates (that show when you try to restore a database). They're the previous 2 backups.

**Comment by ltguillaume** [comment]
Have you had a look at the dates of the files? (They show up when you try to restore a database). They're the previous 2 backups, which you can use when you find out issues later on, when a new backup was already made.

**Comment by Ibuprophen** [comment]
Ahhh... So they're there to help with a type of comparison to aid in determining what may have went wrong and where between backups (previous to current). 

If I'm correct so far... 

Am I correct in stating that the .db is the normal backup automatically generated by the app and the .db0 is the recent backup made by the user and the .db1 is just a backup of the .db when another, app generated, backup before the new one was generated? 

I think I had stated the above okay... :-) 


~Ibuprophen

**Comment by ltguillaume** [comment]
No, it's just https://en.wikipedia.org/wiki/Backup_rotation_scheme

**Comment by ltguillaume** [comment]
More specifically, .db1 is the oldest of the three and will be removed as soon as a new backup is made (either manually or automatically). Then, .db0 will be renamed to .db1 and the current .db renamed to .db0. As soon as that's done, the new backup is made (to .db).

**Comment by Ibuprophen** [comment]
I had just compared my statement to that url and I was about 75% correct... LMAO! 

I was wrong about the members manual backup portion... 

I appreciate this clarification! 

Thank you very much @ltGuillaume... 


~Ibuprophen

**Comment by Ibuprophen** [comment]
Just a quick suggestion @ltGuillaume regarding questions asked between the Github, XDA and other sources... 

It would be great if you could, sometime, place select ones on Github (or elsewhere) as a Wiki/Q&A/FYI/Guide/etc... 

I only suggest this since many individuals may not realize/are aware of them. 

Only a friendly suggestion here without opening a new issue topic... :-) 

Thanks a Bunch! 


~Ibuprophen
