### ISSUE TITLE
Holiday Wishes...

### ISSUE THREAD

**Issue by Ibuprophen** [ltguillaume/droidshows#64]
I just wanted to wish @ltGuillaume Family and Friends the Best Wishes, Happy Holidays and a Happy New Year!!! 

I hope this year ends even more Uplifting and Promising as the last (bumpy) year has ended with!! 

Take care My Friend. 

~Ibuprophen

**Comment by ltguillaume** [comment]
Thanks, really appreciate that! Wishing you the same of course! :-)
