### ISSUE TITLE
Feature request: Export to calendar

### ISSUE THREAD

**Issue by supermamie** [ltguillaume/droidshows#67]
I've found the request about notifications and I'm totally OK with that, but do you think it would be possible to export things to the calendar in my device ?

Like a button on an episode to export it. (One per one should be more feasible than a whole season at once)

With this way, you don't have tohandle the air time, each user will adapt (full day event, in the evening, the day after…)

It would just be simplier than entering everything manually.

Thanks for this app

**Comment by ltguillaume** [comment]
That I can do! Please try this beta then. If you click on the air date in the episode details, it should get you to the calendar app.

https://github.com/ltGuillaume/DroidShows/releases/download/7.8.0/DroidShows_7.9.0beta4.apk

**Comment by supermamie** [comment]
Awesome!
Thanks.

**Comment by ltguillaume** [comment]
I just released the stable version of 7.9.0. This feature is included.
