### ISSUE TITLE
Feature request: Notifications

### ISSUE THREAD

**Issue by yaomtc** [ltguillaume/droidshows#71]
The ability for the app to notify me when a new episode of a show I'm watching is airing soon would be very useful, especially for shows with less predictable schedules.

**Comment by ltguillaume** [comment]
Hi! :-)

Please have a look at https://github.com/ltGuillaume/DroidShows/issues/45
Also, have a look at https://github.com/ltGuillaume/DroidShows/issues/67

**Comment by yaomtc** [comment]
> If you click on the air date in the episode details, it should get you to the calendar app.

Oh, I didn't notice this! Thanks. That takes care of what I need.
