### ISSUE TITLE
Restoring tv shows dialog limited to 100

### ISSUE THREAD

**Issue by casperklein** [ltguillaume/droidshows#73]
After a fresh install I did a restore of my tv shows (more than 100) from backup. The dialog however seems to be limited to 100:

![droidshows](https://user-images.githubusercontent.com/590174/56569981-540d7000-65ba-11e9-9e9f-7c421a4e1ce0.png)

It keeps adding tv shows (while staying at 100%) and then finish successfully.

**Comment by ltguillaume** [comment]
Thanks! That's an unintended side effect of the last update. Could you be so kind to test the following version? :)
[DroidShows_7.9.6test.zip](https://github.com/ltGuillaume/DroidShows/files/3113489/DroidShows_7.9.6test.zip)

**Comment by casperklein** [comment]
Thx, that fixed it.

**Comment by casperklein** [comment]
Another very small issue: After restoring, in the top dropdown menu, "DroidShows" is selected. However, all tv shows (also archived ones) are displayed.
To fix that, you can select "Archive" and then "DroidShows" again. Now only the current tv shows are displayed as intended.

**Comment by ltguillaume** [comment]
Wow, I really screwed up that last update. Thanks for reporting, I'll fix that before the next official release, too

**Comment by ltguillaume** [comment]
Does this fix it for you? :)
[DroidShows_7.9.6test.zip](https://github.com/ltGuillaume/DroidShows/files/3116477/DroidShows_7.9.6test.zip)

**Comment by casperklein** [comment]
Unfortunately, no.

**Comment by ltguillaume** [comment]
Found some code that didn't apply anymore. Have a try. I tested it about 4 times, seems to work fine now. Thanks for your patience *blush
[DroidShows_7.9.6test.zip](https://github.com/ltGuillaume/DroidShows/files/3117391/DroidShows_7.9.6test.zip)

**Comment by casperklein** [comment]
Works :) thx
