### ISSUE TITLE
Pull Down Feature Issue... 

### ISSUE THREAD

**Issue by Ibuprophen** [ltguillaume/droidshows#74]
I had just noticed that, after selecting TheTVDB Mirror box, the Pull Down Feature to update the shows doesn't work. 

It does work when selecting the Update option in the Menu. 

Not a show stopper for me but, I just wanted to bring this to your attention. 

Thanks a bunch! :-) 

~Ibuprophen

**Comment by ltguillaume** [comment]
Choosing that mirror option has got nothing to do with pull-to-refresh. I just tested it and it works fine. So there's something else going on. Can you describe in more detail what happens when it fails (and how it exactly fails)?

**Comment by Ibuprophen** [comment]
This issue is a challenging one to put into words and/or Image Screenshots but, even though I don't do this often (on an as needed basis), I ended up performing the following Screen Recording of what exactly I'm referring to (I had zipped up the video to help reduce the size). 

[Pull.Down.Issue.Example.DroidShows.mp4.zip](https://github.com/ltGuillaume/DroidShows/files/3125350/Pull.Down.Issue.Example.DroidShows.mp4.zip)

I did start off with showing you, first, the DroidShows version and what settings I typically have selected. 

I really hope that this is okay since the brief video "says it all"... LOL! 

Thanks a bunch! :-) 


~Ibuprophen

**Comment by ltguillaume** [comment]
Please try this one: 
[DroidShows_7.9.6pull.zip](https://github.com/ltGuillaume/DroidShows/files/3125467/DroidShows_7.9.6pull.zip)

**Comment by Ibuprophen** [comment]
That one works GREAT!!! 

I see that the video was much more helpful than trying to explain with text and Screenshots... LMAO! :-) 


~Ibuprophen

**Comment by Ibuprophen** [comment]
I'll close this issue as RESOLVED... 

Thank you very much My Friend! :-) 


~Ibuprophen

**Comment by ltguillaume** [comment]
It did indeed. The video allowed me to quickly figure out that it wasn't the option that caused it, but the fact that you repeated the update via pull-to-refresh multiple times in one run :) There was a bug there. Apart from that, your report pushed me to figure out another annoying issue I gave up fixing a long time ago, so thanks for that, too ;)

**Comment by Ibuprophen** [comment]
It wasn't a problem with providing the video. It just took me too much "thinking time" to realize that the video was the best way to explain. 

I really don't use this video feature much at all. I also realized that I could have done this on a number of occasions that could have saved allot of time as well. 

Bonus! :-) 


~Ibuprophen

**Comment by ltguillaume** [comment]
...and so we both learned something 👍
