### ISSUE TITLE
Unmatched Episodes Not Highlighted...  

### ISSUE THREAD

**Issue by Ibuprophen** [ltguillaume/droidshows#75]
Hello Again! :-) 

The following Screen Recording attachment reflects future episodes that are not highlighted as the others are (happens for specials as well). 

[Unmatched.Episodes.Not.Marked-DroidShows.1.zip](https://github.com/ltGuillaume/DroidShows/files/3179220/Unmatched.Episodes.Not.Marked-DroidShows.1.zip)

Also, this is the first time I had experienced this myself and wanted to bring this to your attention. It's not a real big deal with me. 

Thanks a bunch! 

~Ibuprophen

**Comment by ltguillaume** [comment]
What do you mean with "unmatched"? Do you mean "unwatched" (unseen)?

The upcoming episodes are not yet aired, why should they be highlighted?

I had a real hard time keeping up with this video: you switched screens so quickly that the codec didn't even have time to properly show the text. So I'm guessing you wanted to show that some shows with unseen episodes were highlighted, while others were not. I think this indicates that you misunderstood when shows are highlighted: they are *only* highlighted when there are unseen episodes _that have already been aired_.

**Comment by ltguillaume** [comment]
And why did you check/uncheck the option to include specials? Afterwards, I think you only showed series that didn't have any specials anyway, so the count wouldn't have been changed anyway.

**Comment by Ibuprophen** [comment]
I did mean "not watched"... Sorry for the misspelling. 

Regarding the video, I wasn't aware of the speed of my actions. I'll know this if I need to provide another one. 

I was under the impression that the text would be "bold" for those not marked as being watched. 

Am I wrong regarding the text being bold only for those not marked AND the date has to be on or before the current date? 

It may be just one of those days for myself... LOL! 


~Ibuprophen

**Comment by ltguillaume** [comment]
What text exactly? Which line and where?

Ages ago, I may have used bold text for the "Next episode:" line to indicate something, but I can't even remember anymore what I did back then. It's been about 2 years or more since I started using "setEnabled()", which presents as either white or gray text.

**Comment by Ibuprophen** [comment]
The White text is what I mean by bold.

**Comment by ltguillaume** [comment]
So where aren't they white? Please provide a screenshot  and explain/mark what you expected to be different.

**Comment by Ibuprophen** [comment]
I had attached a screenshot with the highlighted areas of what I was referring to. 

[Example1](https://user-images.githubusercontent.com/18060271/57742107-cb9c5f80-768d-11e9-9718-f49ce08f1d4e.png)


~Ibuprophen

**Comment by ltGuillaume** [comment]
That is the intended behavior.

**Comment by ltguillaume** [comment]
[DroidShows_7.9.7+mark_unwatched.zip](https://github.com/ltGuillaume/DroidShows/files/3180801/DroidShows_7.9.7%2Bmark_unwatched.zip)
Like this then?

**Comment by Ibuprophen** [comment]
Awesome! :-)) 

I know that this was something minor and I do really appreciate your time and patience with me as well. :-) 

The following is an example/comparison reflecting Before (I had updated the app with the one you had just provided) and After (Updating the app). 

[Example-Comparisons](https://user-images.githubusercontent.com/18060271/57793457-5c674f80-770f-11e9-9494-e065c2f13431.png)

Unless you prefer otherwise, I'll just close this issue as being (very happily) Resolved My Friend. 


~Ibuprophen
