### ISSUE TITLE
Minor Versioning Question... 

### ISSUE THREAD

**Issue by Ibuprophen** [ltguillaume/droidshows#77]
I just wanted to let you know that, though I know the versioning you had used but, it may be a minor confusion with other users. 

Basically, your release reflects "v7.9.9", your download is labeled "v7.9.8a" and the actual app version is "v7.9.8".

I hope that I had explained this okay via text... :-) 

Thanks a Bunch My Friend! :-P 

~Ibuprophen

**Comment by ltguillaume** [comment]
The release notes already state:

#### 7.9.8a == 7.9.9
- [x] Fixed "simple check to prevent "Update all shows" from being triggered multiple times"
- [x] Version bump for F-Droid (https://github.com/ltGuillaume/DroidShows/issues/76)
