### ISSUE TITLE
Connection error to TheTVDB

### ISSUE THREAD

**Issue by bipox** [ltguillaume/droidshows#78]
Hi and thanks for making this app!

Just reporting this error. I also tried the server mirror in the options.

**Comment by Ibuprophen** [comment]
I have this latest version (v7.9.9) and I had just updated the shows (minutes ago) using both server options without any issues. 

I personally can't duplicate your issue on 2 of my devices so I'll just bump this to @ltGuillaume. 


~Ibuprophen

**Comment by ltguillaume** [comment]
I did reproduce the problem just now, but somewhere halfway through my shows, it started to pick up and update the shows again. This has to be related to TheTVDB, can't be DroidShows-related. Just try again and see if it works 😃

Update: just updated all shows without a glitch.

**Comment by ltguillaume** [comment]
Thera ya go: https://forums.thetvdb.com/viewtopic.php?t=59699

**Comment by bipox** [comment]
Well sorry about that. I did check tvdb was online before writing the report.

**Comment by ltguillaume** [comment]
@bipox No worries of course, thx for taking the time to report!
