### ISSUE TITLE
Duplicate entries

### ISSUE THREAD

**Issue by theAkito** [ltguillaume/droidshows#79]
When adding a TV series, which the app then does not register, which leads you to adding it again, it can happen that your TV series entry in the list can be duplicated. Not only that, but the seasons within an entry get duplicated as well. See picture below, to understand. 

It should be only 1 entry of "House" with only 8 seasons, not 3x8 in each 3 entries:
![](https://i.imgur.com/loaDWMz.jpg)

Additional information :
It could be possibly related to a bad internet connection.

**Comment by ltguillaume** [comment]
But... you get to watch 24 seasons of House! Lucky you!

Looks like a fringe situation, but I may have fixed it with this build, please have a look if you can still reproduce the issue with the attached apk.
[DroidShows_7.9.9a.zip](https://github.com/ltGuillaume/DroidShows/files/3809979/DroidShows_7.9.9a.zip)

Thanks for reporting the issue!

**Comment by ltguillaume** [comment]
@Akito13 Is it gone with DroidShows 7.9.9b? ([see here](https://github.com/ltGuillaume/DroidShows/releases))

**Comment by JonathanMaes** [comment]
I just started having the same issue on Android 13; for a given season, its episodes appear either 0, 1, 2, 3 or 4 times (so each season by itself has a consistent amount of duplicates for each episode, but different seasons have different amounts of such duplicates). Contrary to the author of this issue, I don't have any duplicate series themselves, though.

As an example, Picard season 3: episode 1 is missing, while all other episodes are duplicated.
<img src="https://github.com/ltguillaume/droidshows/assets/26205522/123f408a-13d7-4cfb-af04-b6460322e0d5" data-canonical-src="https://gyazo.com/eb5c5741b6a9a16c692170a41a49c858.png" width="200" />

I have inspected yesterday's .db backup using a desktop SQL viewer, and everything seems to be fine with it (no duplicates). Closing and re-opening the app does not change anything, nor does restoring yesterday's .db backup, or clearing the cache and all data through the Android settings menu.

Re-installing the app and then loading yesterday's .db save does not change anything either.

**Comment by theAkito** [comment]
> I'm gonna try re-installing the app now, then loading yesterday's .db save, to see if that works.

You might want to gather a little bit more evidence before that. For example, screenshots & logs, if possible.

Perhaps the app's maintainer knows some other method of checking out where it is saved, if it is not inside the database. Or maybe reading from the database is faulty.



> Re-installing the app and loading yesterday's .db save does not change anything either, the missing episodes are still missing even though I can clearly see them in the SQL viewer.

Before re-installing etc. you should create a full backup of the entire app data. There's probably some other places, where caches & other temporary files are saved.

**Comment by JonathanMaes** [comment]
I did not expect such a quick reply, I added a screenshot as example but I do not have enough Android experience to provide logs. I also cleared the cache etc. but nothing changed, so I'm really dumbfounded how this issue could just appear out of nowhere and persist through multiple installs and reboots.

**Comment by ltguillaume** [comment]
There's no need for more information on this: it's a recent problem with the TheTVDB API: if I check the raw data that the API gives DroidShows, I see entirely lost seasons or doubled/tripled episodes.

You may contact the people at TheTVDB, but officially the support for APIv1, used by DroidShows, has been stopped for quite a while now.

You may be better off with a switch to https://github.com/warren-bank/Android-Tiny-Television-Time-Tracker/ but currently the migration from DroidShows seems to have some issues: https://github.com/warren-bank/Android-Tiny-Television-Time-Tracker/issues/2

**Comment by JonathanMaes** [comment]
I see, thanks for the suggestion.
Well, thanks for developing this app anyway, it has served me well up to now :)
