### ISSUE TITLE
Pass captcha requests on to users

### ISSUE THREAD

**Issue by LivInTheLookingGlass** [ltguillaume/droidshows#80]
When requesting info for some TV-MA rated shows, tvdb will throw a captcha request. As it stands now, the app will either throw an error saying it can't connect to tvdb if that is the only search result, and otherwise show an entry titled something like "403 Forbidden Content".

An example of this can be seen by searching for "Demon".

**Comment by LivInTheLookingGlass** [comment]
Another example can be seen at https://github.com/Flexget/Flexget/issues/1137

**Comment by Ibuprophen** [comment]
Huh... That's something new to me... 

Does the following image reflect what your referring to? 

[DroidShows](https://user-images.githubusercontent.com/18060271/68547711-ad03f080-03b2-11ea-9110-ad5537e1449a.jpg)

If so, then this can be confirmed on my end. It looks like it happens using the Mirror option as well. 

While awaiting further guidance from @ltGuillaume, I'll take a look at TheTVDB Forum to see if any helpful information is there as well. 


~Ibuprophen

**Comment by ltguillaume** [comment]
Hi! Could you please point me to the location where this "Demon" show is in fact available, but behind a captcha, as you state? (https://www.thetvdb.com/search?q=demon doesn't give me a "Demon" at all.) The only thing I can find is that these `403: Prohibited Content` errors in fact mean that TheTVDB doesn't allow these shows to be in their database _at all_.

Also, the FlexGet issue you pointed at seems to be a different 403 altogether (`403 Client Error: Forbidden`).

**Comment by LivInTheLookingGlass** [comment]
So digging through on the website, it looks like its supposed to point towards this show. Not 100% sure though.

https://www.thetvdb.com/series/how-not-to-summon-a-demon-lord

**Comment by Ibuprophen** [comment]
FWIW, I had taken a look at TheTVDB Forum and had noticed that they've been experiencing some sporadic "up/down" issues with the server that seem to be either "in part" and/or "fully". 

The following example posts does reflect this: 

https://forums.thetvdb.com/viewtopic.php?f=3&t=59699

https://forums.thetvdb.com/viewtopic.php?f=122&t=59912


On another note for @ltGuillaume, I just noticed recent announcements and such regarding TheTVDB API v2 & v3. 

The following are just 2 of them that seems to highlight them:

https://forums.thetvdb.com/viewtopic.php?f=17&t=22325

https://forums.thetvdb.com/viewtopic.php?f=17&t=59456

Just a personal note to help out. 

Thanks a bunch! :-) 


~Ibuprophen

**Comment by ltguillaume** [comment]
> FWIW, I had taken a look at TheTVDB Forum and had noticed that they've been experiencing some sporadic "up/down" issues with the server that seem to be either "in part" and/or "fully".
> 
> The following example posts does reflect this:
> 
> https://forums.thetvdb.com/viewtopic.php?f=3&t=59699
> 
> https://forums.thetvdb.com/viewtopic.php?f=122&t=59912

This has nothing to do with this issue. It did have everything to do with https://github.com/ltGuillaume/DroidShows/issues/79.
 
> On another note for @ltGuillaume, I just noticed recent announcements and such regarding TheTVDB API v2 & v3.
> 
> The following are just 2 of them that seems to highlight them:
> 
> https://forums.thetvdb.com/viewtopic.php?f=17&t=22325
> 
> https://forums.thetvdb.com/viewtopic.php?f=17&t=59456
> 
> Just a personal note to help out.
> 
> Thanks a bunch! :-)
> 
> ~Ibuprophen

I know, I'll be looking into V3 if V1 starts making real issues. I'm just happy I didn't go through with implementing V2 if V3 is already coming 'round 😜

@gappleto97 I have no clue as to what's supposed to be happening with those TV-MA rated shows and how to circumvent these 403's, to be honest. Is there simply no info about it anywhere? If I read the issue you linked to correctly, this was a completely different thing, where the captcha was coming from Cloudflare, _not_ from TheTVDB in order to validate you wanted to see info on TV-MA rated shows. Right?

**Comment by ltguillaume** [comment]
@gappleto97 I'm beginning to think this has something to do with the big pile of shite the API currently is. I'm gonna wait until they fix their mess, first. See https://github.com/ltGuillaume/DroidShows/issues/81

**Comment by ltguillaume** [comment]
@gappleto97 This was indeed related to the API issues TheTVDB.com had. I just added that Demon thing:

![screenshot-20191126-234916](https://user-images.githubusercontent.com/4777345/69679069-84187680-10a7-11ea-8146-dc8e5b0dc800.png)

**Comment by LivInTheLookingGlass** [comment]
How weird. Wonder what their API is doing that that happened

**Comment by ltguillaume** [comment]
It was completely botched. Go see their forum called "Developers" if you want more info, but it does seems to have been resolved 😃
