### ISSUE TITLE
[Feature Request] Password Protection or App lock

### ISSUE THREAD

**Issue by ghost** [ltguillaume/droidshows#82]
Every once in a while, I lend my phone to someone for whatever reason. I would like to have a passcode lock, so I can at least can the shows I watched private. Even from physical people I meet.

**Comment by beerisgood** [comment]
Did you use a lock screen already? This is the best protection.
Also DroidShows doesn't save any private data and this sounds overkill for that

**Comment by ltguillaume** [comment]
I reckon that if you would like to do this for DroidShows, then there are more apps you'd like to password protect before lending your phone. There are a bunch of apps that allow you to do so for multiple apps at once. Perhaps you could see if something like that works for you.

Or even better, you can create a second account on your device.

More info:
https://www.androidpit.com/lock-individual-apps-on-smartphone
https://www.androidauthority.com/best-applocks-privacy-lock-apps-android-750699/

**Comment by ghost** [comment]
Sure. But App locks aren't that great, there are sure very easy ways to make the app lock fail. A simple pattern lock might be ok though?

>Also DroidShows doesn't save any private data and this sounds overkill for that.

I understand.
