### ISSUE TITLE
Open in Kodi with X addon

### ISSUE THREAD

**Issue by rdscorreia74** [ltguillaume/droidshows#83]
Hi there,
Is it possible open a given episode in Kodi using a given addon?
If not, would it be possible to add such a feature?
Thanks in advance.

**Comment by ltguillaume** [comment]
No, sorry, that's not possible. I have no idea if Kodi supports anything like that either, haven't seen a feature like this any other app yet.

**Comment by rdscorreia74** [comment]
Wako, which is sort of similar to DroidShows supports addons.
Two of their addons, Helios and Nomos, have that feature.
Too bad those are closed source.
I have been using Wako for some time and I am looking into alternatives because:
- wako is not open source.
- wako dies every two minutes of using for no apparent reason
- wako is terribly slow, probably due to trakt backend being slow
- wako doesn't have an option for local database
- wako is flooded with ads

It is excellent at sending the information to kodi telling it that I want to watch the X episode of the Y tvshow. But only when it doesn't die before sending the trigger to kodi...

I didn't know about DroidShows, its' simplicity and the choice for a local database. It would be cool if it had a way to somehow import trakt information. Only as way to move over from trakt to DroidShows. But I don't know if it's even possible to export trakt's data.

**Comment by ltguillaume** [comment]
Wako is a complete Kodi remote control, with access to Kodi's library and everything, so Helios & Nomos simply give the command to play a specific episode back to Kodi. Since Wako isn't open-source, and I can't find proper documentation about if and how this would be possible with Kodi directly (via an Andoid Intent or something), I don't think it's possible without implementing an entire remote control module for Kodi. Obviously, that is well beyond the scope of DroidShows.

If you can find another way (say, a remote control app for Kodi that could handle an Intent from another app to play a specific episode) and it's well-documented, I'll have another look.

**Comment by casperklein** [comment]
Afaik Wako does not play local files you already got, instead it just streams them from internet sites, which in most countrys is not legal. What wako does is just sending URLs to stream to Kodi..

**Comment by ltguillaume** [comment]
In that case, it would be wholly impossible for DroidShows to do anything like that for sure. I thought maybe that Kodi had a way to receive a request to play a certain locally saved episode via its library and that _that_ is what you wanted. But if it's the torrent-streaming Helios and/or Nomos allow, then sorry, you should look elsewhere.

**Comment by rdscorreia74** [comment]
> Afaik Wako does not play local files you already got, instead it just streams them from internet sites, which in most countrys is not legal. What wako does is just sending URLs to stream to Kodi..

Exactly. As a matter of fact, I never said the files would come out of the android phone/tablet to be played on the Kodi device.
I just meant that DroidShows could somehow send the metadata to kodi which in return would try to run it either from it's local library or through an addon.

**Comment by ltguillaume** [comment]
Well, if it would be from different sources (e.g. local library or (several) Kodi plugins), then I'm rather sure there isn't any way to do that with Kodi.

If you find some kind of API for that, I could look at it, but I couldn't find anything like that.

**Comment by rdscorreia74** [comment]
Well, I am not a programmer and I don't know anything about API's.
If they did it with Wako it's because there's some way.
It's just that they are using Trakt, invasive ads and I would much rather use my own local database and sitck to no ads or at least non invasive ads cached locally on the device.
That's why I thought DroidShows would be the perfect candidate to replacing Wako...
