### ISSUE TITLE
compile to APK

### ISSUE THREAD

**Issue by gspeiliu** [ltguillaume/droidshows#86]
How can I compile the source code into apk? 
Does the original compile tool is Eclipse ADT?
Thanks for your help. :-)

**Comment by ltguillaume** [comment]
Yeah I'm still using Eclipse for this one.

**Comment by gspeiliu** [comment]
Hi,
Another question about the compilation.
Does any other automatic build tool are you using? like Ant, Maven etc. Thanks ~~

**Comment by ltguillaume** [comment]
Nope. DroidShows has no dependencies other than the Android SDK.
