### ISSUE TITLE
Feature request: Possibility to edit seen time as well as date 

### ISSUE THREAD

**Issue by amadeous** [ltguillaume/droidshows#87]
Hi there!

I hope you're doing fine. Thank you for that great app that still works after all these years!

A timestamp is used to represent the moment an episode is seen. We can then edit the seen date but not the seen time (approx., no need for seconds). Could it be easily implemented?

Motivation: I admit I sometimes forget to check episodes after seeing them. For now I can only edit the date but not the time in the day. The current trick is to mark them as seen at the same time on a following day and edit the day.

Thanks a lot!

**Comment by ltguillaume** [comment]
Hi, doing fine, thx! :)

The only reason I added the time to the "seen" field was to allow both the Log to display episodes seen on the same day in the proper order and to allow for the feature "Mark next episode starting from the most recently watched" (what a stupid description, come to think of it). I never thought ppl would actually find it useful to specify the actual time, but I do see your point. I have added a time picker in this build, please have a look and test for problems:
[DroidShows_7.10.0.zip](https://github.com/ltGuillaume/DroidShows/files/4650952/DroidShows_7.10.0.zip)

If you're using F-Droid builds, it will be available in 2-3 days.

**Comment by amadeous** [comment]
Wonderful! Quickly implemented!

It works for me. Should _date_ in the `messsages_edit_seen_date` field in the strings be replaced for something more precise such as _moment_ or _datetime_?

**Comment by ltguillaume** [comment]
If it would be a small thing to change it for all languages _and_ if there would be a thing that would sound at least OK-ish (_Edit seen timestamp_?), I might have done that.

You're totally right, though, it doesn't really describe the function completely anymore.

**Comment by amadeous** [comment]
_Edit seen timestamp_ seems fine. It would be _Modifier l'horodatage_ in french.
The string could be changed now and translated later on (when [adding a potential statistics screen](https://github.com/ltGuillaume/DroidShows/issues/88)? :wink:).

**Comment by ltguillaume** [comment]
The new release includes the changed string for some languages.

**Comment by amadeous** [comment]
Splendid! I saw you changed the french translation in the french string file as well. Thank you for this new feature!

**Comment by ltguillaume** [comment]
All good! Thanks for taking the time to test it 🙂
