### ISSUE TITLE
"No shows found." List sometimes empty after update to version 6.3

### ISSUE THREAD

**Issue by cvzi** [ltguillaume/droidshows#9]
After I updated to the newest version, everything seemed to work fine. But after adding a new show and restarting the app, it now only says "No shows found."

If I try to add a show that I already had in my list, it shows a star instead of the "+"-icon. So I'm guessing the database is still intact.

Logcat of startup:

```
E/DroidShows(19810): Error populating TVShowItems or no shows added yet
W/System.err(19810): java.lang.NullPointerException
W/System.err(19810):    at nl.asymmetrics.droidshows.DroidShows.createTVShowItem(DroidShows.java:891)
W/System.err(19810):    at nl.asymmetrics.droidshows.DroidShows.getSeries(DroidShows.java:912)
W/System.err(19810):    at nl.asymmetrics.droidshows.DroidShows.onCreate(DroidShows.java:171)
W/System.err(19810):    at android.app.Activity.performCreate(Activity.java:5451)
W/System.err(19810):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
W/System.err(19810):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2292)
W/System.err(19810):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2386)
W/System.err(19810):    at android.app.ActivityThread.access$900(ActivityThread.java:169)
W/System.err(19810):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1277)
W/System.err(19810):    at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err(19810):    at android.os.Looper.loop(Looper.java:136)
W/System.err(19810):    at android.app.ActivityThread.main(ActivityThread.java:5476)
W/System.err(19810):    at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err(19810):    at java.lang.reflect.Method.invoke(Method.java:515)
W/System.err(19810):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
W/System.err(19810):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
W/System.err(19810):    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
W/System.err(19810):    at dalvik.system.NativeStart.main(Native Method)
```

Edit:
If I go to the settings and click on "Sort by name"/"Sort by unseen", the list of shows appears. After restarting the list is empty again

**Comment by ltguillaume** [comment]
Yes, the database will still be intact and you will not have lost any data. But are you sure you added this new tv show while running v6.3? This issue was only a bug in v6.2. You can try to create a backup of your current database and then restore the same database again. It should work again after you have confirmed to update all shows upon restore. If not, send me the database backup you just made by uploading the file [link removed] and I'll fix it.

**Comment by cvzi** [comment]
Backup and and restoring did not change anything. I uploaded my backup on your link.

**Comment by ltguillaume** [comment]
Fringe was the problem. I renamed the backup you uploaded to .previous, so you can download and restore the file currently named DroidShows.db.

**Comment by cvzi** [comment]
It works. Many thanks!
