### ISSUE TITLE
Poster gets closed after device rotation

### ISSUE THREAD

**Issue by geniuslittleteddy** [ltguillaume/droidshows#93]
Steps to reproduce:
1. open a post
![Screen Shot 2020-08-17 at 8 43 45 PM](https://user-images.githubusercontent.com/26519038/90397441-6b833d00-e0ca-11ea-9d7a-51c5193ebe21.png)
1. Click a small pic on a post
![Screen Shot 2020-08-17 at 8 43 53 PM](https://user-images.githubusercontent.com/26519038/90397468-79d15900-e0ca-11ea-9452-e5cf8e51832e.png)
2. Rotate screen to to see details
![Screen Shot 2020-08-17 at 8 44 00 PM](https://user-images.githubusercontent.com/26519038/90397505-8950a200-e0ca-11ea-95ac-deb00983a4f9.png)

The pic disappear so I have to repeat the previous steps to reopen

**Comment by ltguillaume** [comment]
You're right, this will be fixed in the next version.
