### ISSUE TITLE
API change in TVDB

### ISSUE THREAD

**Issue by igoralmeida** [ltguillaume/droidshows#97]
Maybe we should be worried about TheTVDB charging for API access?
See more in https://github.com/red-coracle/episodes/issues/43 and linked issue in SeriesGuide

**Comment by ltguillaume** [comment]
Worried, yes. Do domething about it, not yet. TheTVDB has been doing a lot of API changes, too, but in the end APIv1 is still working. Let's see if they actually follow through with this.

**Comment by c33s** [comment]
yesterday i tried to add/search for a series and i got back an connection error. as i can connect to all other services on my phone, i assume that the apiv1 of tvdb is finally closed. :disappointed:

also see https://github.com/thetvdb/v4-api/issues/290

an update to a working api would be awesome

**Comment by ltguillaume** [comment]
Still works here, so I expect this was a temporary issue.

**Comment by c33s** [comment]
> Still works here, so I expect this was a temporary issue.

thanks. yes it was a temp isse.
